"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

const empty = { label: "BREAKING", kind: "breaking", message: "", url: "", priority: 5, status: "active", starts_at: "", ends_at: "" };
export default function AdminAlerts() {
  const [rows, setRows] = useState<any[]>([]); const [form, setForm] = useState<any>(empty); const [msg,setMsg]=useState("");
  useEffect(()=>{ load(); },[]);
  async function load(){ const {data,error}=await supabase.from("site_alerts").select("*").order("created_at",{ascending:false}); if(error)setMsg(error.message); setRows(data||[]); }
  async function save(e:any){ e.preventDefault(); setMsg(""); const payload={...form, starts_at:form.starts_at||null, ends_at:form.ends_at||null}; const {error}=await supabase.from("site_alerts").insert(payload); if(error){setMsg(error.message);return;} setForm(empty); load(); }
  async function setStatus(id:string,status:string){ await supabase.from("site_alerts").update({status}).eq("id",id); load(); }
  return <main className="mx-auto max-w-6xl px-4 py-10"><h1 className="text-5xl font-black text-hgnNavy">Breaking / Ferry / Weather Alerts</h1><p className="mt-2 text-slate-600">Create site-wide bars that appear above the masthead.</p>{msg&&<div className="mt-4 text-hgnBlue font-bold">{msg}</div>}<form onSubmit={save} className="hgn-card mt-6 grid gap-4 p-6 md:grid-cols-2"><input className="hgn-input" placeholder="Label e.g. BREAKING" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/><select className="hgn-input" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="breaking">Breaking</option><option value="weather">Weather</option><option value="ferry">Ferry</option><option value="community">Community</option></select><input className="hgn-input md:col-span-2" required placeholder="Alert message" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><input className="hgn-input" placeholder="Link URL optional" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><input className="hgn-input" type="number" placeholder="Priority" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})}/><input className="hgn-input" type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/><input className="hgn-input" type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/><button className="hgn-btn-primary md:col-span-2">Publish alert</button></form><div className="mt-8 grid gap-4">{rows.map(r=><article key={r.id} className="hgn-card p-5"><div className="text-xs font-black uppercase text-hgnBlue">{r.status} • {r.kind}</div><h2 className="mt-1 text-2xl font-black text-hgnNavy">{r.label}: {r.message}</h2><p className="mt-1 text-sm text-slate-500">{r.starts_at||"now"} → {r.ends_at||"open"}</p><div className="mt-3 flex gap-2"><button onClick={()=>setStatus(r.id,"active")} className="hgn-btn-primary">Active</button><button onClick={()=>setStatus(r.id,"paused")} className="hgn-btn-dark">Pause</button><button onClick={()=>setStatus(r.id,"expired")} className="rounded-full bg-hgnBlue px-4 py-2 text-sm font-black text-white">Expire</button></div></article>)}</div></main>
}
