export const weatherLocations = [
  {
    name: "Masset",
    slug: "masset",
    lat: 54.02,
    lon: -132.15,
    forecastUrl: "https://weather.gc.ca/city/pages/bc-85_metric_e.html",
    marineUrl: "https://weather.gc.ca/marine/",
  },
  {
    name: "Old Massett",
    slug: "old-massett",
    lat: 54.10,
    lon: -132.18,
    forecastUrl: "https://weather.gc.ca/city/pages/bc-85_metric_e.html",
    marineUrl: "https://weather.gc.ca/marine/",
  },
  {
    name: "Port Clements",
    slug: "port-clements",
    lat: 53.69,
    lon: -132.18,
    forecastUrl: "https://weather.gc.ca/",
    marineUrl: "https://weather.gc.ca/marine/",
  },
  {
    name: "Tlell",
    slug: "tlell",
    lat: 53.56,
    lon: -131.94,
    forecastUrl: "https://weather.gc.ca/",
    marineUrl: "https://weather.gc.ca/marine/",
  },
  {
    name: "Skidegate",
    slug: "skidegate",
    lat: 53.27,
    lon: -132.00,
    forecastUrl: "https://weather.gc.ca/",
    marineUrl: "https://weather.gc.ca/marine/",
  },
  {
    name: "Daajing Giids",
    slug: "daajing-giids",
    lat: 53.25,
    lon: -132.08,
    forecastUrl: "https://weather.gc.ca/",
    marineUrl: "https://weather.gc.ca/marine/",
  },
  {
    name: "Sandspit",
    slug: "sandspit",
    lat: 53.25,
    lon: -131.81,
    forecastUrl: "https://weather.gc.ca/city/pages/bc-83_metric_e.html",
    marineUrl: "https://weather.gc.ca/marine/",
  },
]

export const tideStations = [
  {
    name: "Masset",
    slug: "masset",
    area: "North Graham Island",
    lat: 54.02,
    lon: -132.15,
    stationCode: "09910",
    stationName: "Masset",
    officialUrl: "https://tides.gc.ca/en/stations/09910",
    notes: "Real-time and prediction station for north island marine planning and Masset area references.",
  },
  {
    name: "Daajing Giids / Queen Charlotte",
    slug: "daajing-giids",
    area: "Bearskin Bay / south Graham Island",
    lat: 53.25,
    lon: -132.08,
    stationCode: "09850",
    stationName: "Daajing Giids [Queen Charlotte City]",
    officialUrl: "https://tides.gc.ca/en/stations/09850",
    notes: "Real-time and prediction station useful for harbour, marina and south island planning.",
  },
  {
    name: "Port Clements",
    slug: "port-clements",
    area: "Central Graham Island",
    lat: 53.69,
    lon: -132.18,
    stationCode: "09920",
    stationName: "Port Clements",
    officialUrl: "https://tides.gc.ca/en/stations/09920",
    notes: "Prediction station for Port Clements and central island references.",
  },
  {
    name: "Tlell",
    slug: "tlell",
    area: "East Graham Island",
    lat: 53.56,
    lon: -131.94,
    stationCode: "09860",
    stationName: "Tlell",
    officialUrl: "https://tides.gc.ca/en/stations/09860",
    notes: "Prediction station for east coast conditions around Tlell.",
  },
  {
    name: "Sandspit Marina",
    slug: "sandspit",
    area: "Moresby Island",
    lat: 53.25,
    lon: -131.81,
    stationCode: "09795",
    stationName: "Sandspit Marina",
    officialUrl: "https://tides.gc.ca/en/stations/09795",
    notes: "Prediction station useful for Sandspit, Alliford Bay and Moresby Island travel.",
  },
  {
    name: "Rose Harbour",
    slug: "rose-harbour",
    area: "South Gwaii Haanas",
    lat: 52.15,
    lon: -131.08,
    stationCode: "09713",
    stationName: "Rose Harbour",
    officialUrl: "https://tides.gc.ca/en/stations/09713",
    notes: "Real-time and prediction station for southern Haida Gwaii / Gwaii Haanas references.",
  },
]

export function windyEmbedUrl(lat: number, lon: number) {
  return `https://embed.windy.com/embed2.html?lat=${lat}&lon=${lon}&detailLat=${lat}&detailLon=${lon}&width=650&height=450&zoom=7&level=surface&overlay=wind&product=ecmwf&menu=&message=true&marker=true&calendar=now&pressure=true&type=map&location=coordinates&detail=true&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1`
}
