-- HGN v0.53.0: tourist-season guide expansion and reporting support
-- Run once after v273.

insert into public.hgn_guide_places(slug,name,category,community,latitude,longitude,description,address,phone,website,hours,amenities,caution,featured,source_name,source_url,verified_at,next_review_at)
values
('east-beach-tlell','East Beach at Tlell','Beach','Tlell',53.557,-131.930,'A broad east-coast beach with long walks, driftwood and views across Hecate Strait.',null,null,'https://bcparks.ca/naikoon-park/',null,array['Beach access','Walking'],'Watch tides, surf and quickly changing weather.',true,'BC Parks','https://bcparks.ca/naikoon-park/',now(),current_date+30),
('balance-rock','Balance Rock','Viewpoint','Skidegate',53.269,-131.997,'A well-known roadside viewpoint and short stop between Skidegate and Daajing Giids.',null,null,null,null,array['Roadside stop','Photo opportunity'],'Pull fully off the roadway before stopping.',true,'HGN local guide',null,now(),current_date+60),
('masset-airport','Masset Municipal Airport','Transportation','Masset',54.027,-132.125,'Airport serving Masset and northern Haida Gwaii.',null,null,'https://massetbc.com/visitors/airport/',null,array['Airport','Parking'],null,false,'Village of Masset','https://massetbc.com/visitors/airport/',now(),current_date+30),
('sandspit-airport','K’il Kun Xidgwangs Daanaay Airport','Transportation','Sandspit',53.254,-131.814,'Airport serving Sandspit and Moresby Island.',null,null,'https://www.yvr.ca/en/passengers/flights/regional-airports',null,array['Airport','Parking'],null,false,'Airport operator','https://www.yvr.ca/en/passengers/flights/regional-airports',now(),current_date+30),
('daajing-hospital','Haida Gwaii Hospital and Health Centre','Essential Service','Daajing Giids',53.253,-132.071,'Hospital and emergency health services for southern Haida Gwaii.',null,'250-559-4900','https://www.northernhealth.ca/locations/hospitals/haida-gwaii-hospital-health-centre',null,array['Hospital','Emergency department'],null,true,'Northern Health','https://www.northernhealth.ca/locations/hospitals/haida-gwaii-hospital-health-centre',now(),current_date+30),
('masset-hospital','Northern Haida Gwaii Hospital and Health Centre','Essential Service','Masset',54.012,-132.149,'Hospital and health services for northern Haida Gwaii.',null,null,'https://www.northernhealth.ca/locations/hospitals/northern-haida-gwaii-hospital-health-centre',null,array['Hospital','Emergency department'],null,true,'Northern Health','https://www.northernhealth.ca/locations/hospitals/northern-haida-gwaii-hospital-health-centre',now(),current_date+30),
('mayer-lake','Mayer Lake Rest Area','Rest Stop','Central Graham Island',53.610,-132.050,'A practical roadside stopping area near Mayer Lake.',null,null,null,null,array['Roadside stop','Scenic area'],'Confirm current access and roadside conditions.',false,'HGN local guide',null,now(),current_date+60),
('drivebc-tlell','DriveBC Tlell Camera','Camera','Tlell',53.565,-131.930,'Road-condition camera source for the Tlell area.',null,null,'https://images.drivebc.ca/bchighwaycam/pub/html/www/index-Northern.html',null,array['Road camera','Live source'],null,false,'DriveBC','https://images.drivebc.ca/bchighwaycam/pub/html/www/index-Northern.html',now(),current_date+7),
('drivebc-masset','DriveBC Masset Camera','Camera','Masset',54.010,-132.150,'Road-condition camera source for northern Haida Gwaii.',null,null,'https://images.drivebc.ca/bchighwaycam/pub/html/www/index-Northern.html',null,array['Road camera','Live source'],null,false,'DriveBC','https://images.drivebc.ca/bchighwaycam/pub/html/www/index-Northern.html',now(),current_date+7)
on conflict(slug) do update set
 name=excluded.name,category=excluded.category,community=excluded.community,latitude=excluded.latitude,longitude=excluded.longitude,description=excluded.description,phone=coalesce(excluded.phone,hgn_guide_places.phone),website=coalesce(excluded.website,hgn_guide_places.website),amenities=excluded.amenities,caution=excluded.caution,featured=excluded.featured,source_name=excluded.source_name,source_url=excluded.source_url,verified_at=excluded.verified_at,next_review_at=excluded.next_review_at,updated_at=now();

insert into public.hgn_guide_sources(name,url,category,community,check_frequency_days,notes)
values
('Masset Municipal Airport','https://massetbc.com/visitors/airport/','Transportation','Masset',30,'Official airport visitor information.'),
('Northern Health Haida Gwaii Hospital','https://www.northernhealth.ca/locations/hospitals/haida-gwaii-hospital-health-centre','Essential Service','Daajing Giids',30,'Official hospital details.'),
('Northern Health northern hospital','https://www.northernhealth.ca/locations/hospitals/northern-haida-gwaii-hospital-health-centre','Essential Service','Masset',30,'Official hospital details.')
on conflict(url) do nothing;
