"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import type { GuidePlace } from "@/lib/guide-places"

const icons:Record<string,string>={Beach:"🏖️",Fuel:"⛽",Food:"🍽️","Essential Service":"✚",Transportation:"⛴️",Culture:"◉",Campground:"⛺",Viewpoint:"◭",Camera:"📷","Rest Stop":"●"}
const radians=(n:number)=>n*Math.PI/180
function distanceKm(a:{lat:number;lng:number},b:{latitude:number;longitude:number}){const R=6371,dLat=radians(b.latitude-a.lat),dLng=radians(b.longitude-a.lng);const x=Math.sin(dLat/2)**2+Math.cos(radians(a.lat))*Math.cos(radians(b.latitude))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(x))}

export default function IslandGuideMap({ places, initialCategory = "All" }: { places: GuidePlace[]; initialCategory?: string }) {
  const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),layerRef=useRef<any>(null)
  const[category,setCategory]=useState(initialCategory),[query,setQuery]=useState(""),[selected,setSelected]=useState<GuidePlace|null>(null),[location,setLocation]=useState<{lat:number;lng:number}|null>(null),[locating,setLocating]=useState(false)
  const categories=useMemo(()=>["All",...Array.from(new Set(places.map(p=>p.category)))],[places])
  const filtered=useMemo(()=>places.filter(place=>{if(category!=="All"&&place.category!==category)return false;const haystack=`${place.name} ${place.community} ${place.category} ${place.description} ${(place.amenities||[]).join(" ")}`.toLowerCase();return !query.trim()||haystack.includes(query.toLowerCase().trim())}).sort((a,b)=>location?distanceKm(location,a)-distanceKm(location,b):Number(Boolean(b.featured))-Number(Boolean(a.featured))),[places,category,query,location])
  useEffect(()=>{let cancelled=false;async function load(){if(!mapEl.current||mapRef.current)return;const L=await import("leaflet");if(cancelled||!mapEl.current)return;const map=L.map(mapEl.current,{scrollWheelZoom:false,zoomControl:true}).setView([53.62,-132.02],8);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors",maxZoom:18}).addTo(map);mapRef.current=map;layerRef.current=L.layerGroup().addTo(map)}void load();return()=>{cancelled=true;mapRef.current?.remove();mapRef.current=null}},[])
  useEffect(()=>{async function draw(){if(!mapRef.current||!layerRef.current)return;const L=await import("leaflet");layerRef.current.clearLayers();filtered.forEach(place=>{if(!Number.isFinite(place.latitude)||!Number.isFinite(place.longitude)||!place.latitude||!place.longitude)return;const html=`<div style="width:${place.featured?38:34}px;height:${place.featured?38:34}px;border-radius:999px;background:#fff;border:2px solid #111827;display:flex;align-items:center;justify-content:center;font-size:${place.featured?20:18}px;box-shadow:0 3px 12px rgba(15,23,42,.28)">${icons[place.category]||"●"}</div>`;const marker=L.marker([place.latitude,place.longitude],{icon:L.divIcon({html,className:"",iconSize:[place.featured?38:34,place.featured?38:34],iconAnchor:[17,17]})});marker.bindTooltip(place.name,{direction:"top"});marker.on("click",()=>setSelected(place));marker.addTo(layerRef.current)});if(location)L.circleMarker([location.lat,location.lng],{radius:8,color:"#0369a1",fillColor:"#38bdf8",fillOpacity:1,weight:3}).bindTooltip("You are here").addTo(layerRef.current);if(filtered.length){const valid=filtered.filter(p=>p.latitude&&p.longitude);if(valid.length){const bounds=L.latLngBounds(valid.map(p=>[p.latitude,p.longitude] as [number,number]));mapRef.current.fitBounds(bounds.pad(.14),{maxZoom:11})}}}void draw()},[filtered,location])
  function findMe(){if(!navigator.geolocation)return;setLocating(true);navigator.geolocation.getCurrentPosition(p=>{const here={lat:p.coords.latitude,lng:p.coords.longitude};setLocation(here);mapRef.current?.setView([here.lat,here.lng],11);setLocating(false)},()=>setLocating(false),{enableHighAccuracy:true,timeout:10000})}
  return <div className="grid gap-5 lg:grid-cols-[1.45fr_.75fr]">
    <div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_auto_auto]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search beaches, fuel, ferries, services…" className="rounded-xl border px-4 py-3"/><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border px-4 py-3">{categories.map(item=><option key={item}>{item}</option>)}</select><button onClick={findMe} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white">{locating?"Finding…":"Near me"}</button></div><div ref={mapEl} className="h-[58vh] min-h-[430px] w-full" aria-label="Interactive Haida Gwaii guide map"/></div>
    <aside className="space-y-4">{selected?<article className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.16em] text-hgnBlue">{icons[selected.category]} {selected.category} · {selected.community}</p><h2 className="mt-2 text-2xl font-black">{selected.name}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{selected.description}</p>{selected.address&&<p className="mt-3 text-sm"><strong>Address:</strong> {selected.address}</p>}{selected.hours&&<p className="mt-2 text-sm"><strong>Hours:</strong> {selected.hours}</p>}{selected.phone&&<a href={`tel:${selected.phone}`} className="mt-2 block text-sm font-bold text-hgnBlue">Call {selected.phone}</a>}{selected.caution&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-900">{selected.caution}</p>}<div className="mt-4 flex flex-wrap gap-2">{(selected.amenities||[]).map(item=><span key={item} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{item}</span>)}</div><div className="mt-5 flex flex-wrap gap-3"><a href={`https://www.google.com/maps/dir/?api=1&destination=${selected.latitude},${selected.longitude}`} target="_blank" rel="noreferrer" className="rounded-full bg-slate-950 px-4 py-2 text-sm font-bold text-white">Directions</a>{selected.website&&<a href={selected.website} target="_blank" rel="noreferrer" className="rounded-full border px-4 py-2 text-sm font-bold">Official source</a>}</div></article>:<div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Tap a marker</h2><p className="mt-2 text-sm leading-6 text-slate-600">Details, cautions, directions and official links appear here.</p></div>}
      <div className="max-h-[390px] space-y-2 overflow-auto rounded-3xl border bg-white p-3 shadow-sm">{filtered.map(place=><button key={place.id} onClick={()=>{setSelected(place);mapRef.current?.setView([place.latitude,place.longitude],12)}} className="w-full rounded-2xl p-3 text-left hover:bg-slate-50"><span className="text-xs font-black uppercase tracking-wide text-hgnBlue">{icons[place.category]} {place.category}</span><span className="mt-1 block font-black">{place.name}</span><span className="text-xs text-slate-500">{place.community}{location?` · ${distanceKm(location,place).toFixed(1)} km away`:""}</span></button>)}{!filtered.length&&<p className="p-5 text-sm text-slate-500">No matching guide places.</p>}</div>
    </aside></div>
}
