import Link from "next/link"
import { airportInfo } from "@/lib/live-utilities"
const sections = [
  { title: "Prince Rupert ↔ Skidegate", text: "Main mainland ferry route. Check current conditions, reservation details and terminal notices before travel.", href: "https://www.bcferries.com/current-conditions" },
  { title: "Skidegate ↔ Alliford Bay", text: "Inter-island ferry connecting Graham Island and Moresby Island.", href: "https://www.bcferries.com/current-conditions" },
  { title: "DriveBC", text: "Road conditions, incidents, construction and camera sources.", href: "https://www.drivebc.ca/" },
  { title: "DriveBC road conditions", text: "Official road conditions, closures, incidents and camera sources.", href: "https://www.drivebc.ca/" },
]
export const metadata = { title: "Ferries & Travel" }
export default function TravelPage() { return <main className="mx-auto max-w-6xl space-y-8 px-6 py-8"><header><p className="text-xs font-black uppercase tracking-[0.2em] text-hgnBlue">Haida Gwaii Guide</p><h1 className="mt-2 font-serif text-5xl font-bold">Ferries & Travel</h1><p className="mt-4 max-w-3xl text-slate-600">A practical starting point for ferry routes, airports, road conditions and island travel planning. Confirm times and conditions with the carrier before leaving.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/ferry-info" className="rounded-full bg-slate-950 px-5 py-3 text-sm font-bold text-white">HGN Ferry Desk</Link><Link href="/explore/trackers" className="rounded-full border px-5 py-3 text-sm font-bold">Air & Marine Watch</Link><Link href="/explore/cams" className="rounded-full border px-5 py-3 text-sm font-bold">Island Cams</Link></div></header><section className="grid gap-5 md:grid-cols-2">{sections.map((item) => <a key={item.title} href={item.href} target="_blank" rel="noreferrer" className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">{item.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{item.text}</p><span className="mt-5 inline-flex text-sm font-bold text-hgnBlue">Open official source →</span></a>)}</section><section><p className="text-xs font-black uppercase tracking-[.18em] text-hgnBlue">Air travel</p><h2 className="mt-1 font-serif text-4xl font-bold">Airport information</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{airportInfo.slice(0,2).map((airport)=><a key={airport.href} href={airport.href} target="_blank" rel="noreferrer" className="rounded-3xl border bg-white p-6 shadow-sm"><h3 className="text-2xl font-black">{airport.name}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{airport.description}</p><span className="mt-5 inline-flex text-sm font-bold text-hgnBlue">Open official source →</span></a>)}</div></section></main> }
