import Link from "next/link"
const sections = [
  { title: "Prince Rupert ↔ Skidegate", text: "Main mainland ferry route. Check current conditions, reservation details and terminal notices before travel.", href: "https://www.bcferries.com/current-conditions" },
  { title: "Skidegate ↔ Alliford Bay", text: "Inter-island ferry connecting Graham Island and Moresby Island.", href: "https://www.bcferries.com/current-conditions" },
  { title: "DriveBC", text: "Road conditions, incidents, construction and camera sources.", href: "https://www.drivebc.ca/" },
  { title: "Masset Airport", text: "North-island airport information and local access details.", href: "https://massetbc.com/visitors/airport/" },
]
export const metadata = { title: "Ferries & Travel" }
export default function TravelPage() { return <main className="mx-auto max-w-6xl space-y-8 px-6 py-8"><header><p className="text-xs font-black uppercase tracking-[0.2em] text-hgnBlue">Haida Gwaii Guide</p><h1 className="mt-2 text-5xl font-black">Ferries & Travel</h1><p className="mt-4 max-w-3xl text-slate-600">One practical starting point for ferry routes, airports, road conditions and island travel planning.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/ferry-info" className="rounded-full bg-slate-950 px-5 py-3 text-sm font-bold text-white">HGN Ferry Page</Link><Link href="/explore/cams" className="rounded-full border px-5 py-3 text-sm font-bold">Island Cams</Link><Link href="/explore/map" className="rounded-full border px-5 py-3 text-sm font-bold">Island Map</Link></div></header><section className="grid gap-5 md:grid-cols-2">{sections.map((item) => <a key={item.title} href={item.href} target="_blank" rel="noreferrer" className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">{item.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{item.text}</p><span className="mt-5 inline-flex text-sm font-bold text-hgnBlue">Open official source →</span></a>)}</section></main> }
