export const sourceLinks = [
  {
    title: "Go Haida Gwaii — Visitor Information",
    href: "https://www.gohaidagwaii.ca/visitor-information",
    description: "Official visitor planning and travel information for Haida Gwaii.",
  },
  {
    title: "Haida Tourism — Getting Here",
    href: "https://www.haidatourism.ca/getting-here",
    description: "Visitor travel information including flights to Sandspit and Masset.",
  },
  {
    title: "Parks Canada — Gwaii Haanas",
    href: "https://parks.canada.ca/pn-np/bc/gwaiihaanas/visit",
    description: "Official visitor information for Gwaii Haanas National Park Reserve, National Marine Conservation Area Reserve, and Haida Heritage Site.",
  },
  {
    title: "Haida Heritage Centre",
    href: "https://www.haidaheritagecentre.com/visit/",
    description: "Visitor information for the Haida Heritage Centre at Kay Llnagaay.",
  },
  {
    title: "BC Ferries Current Conditions",
    href: "https://www.bcferries.com/current-conditions",
    description: "Current ferry sailing conditions and terminal status.",
  },
  {
    title: "Environment Canada Weather",
    href: "https://weather.gc.ca/",
    description: "Official public weather forecasts and alerts.",
  },
  {
    title: "Earthquakes Canada — Haida Gwaii Region",
    href: "https://earthquakescanada.nrcan.gc.ca/index-en.php?tpl_region=qci",
    description: "Recent regional earthquake information.",
  },
  {
    title: "EmergencyInfoBC",
    href: "https://www.emergencyinfobc.gov.bc.ca/",
    description: "Provincial emergency updates and public safety information.",
  },
]

export const communities = [
  {
    slug: "masset",
    name: "Masset",
    description: "Northern Haida Gwaii community and service hub with airport access, nearby North Beach, marine activity, shops, food and essential services.",
    highlights: ["Masset Municipal Airport", "North Beach access", "North-end services", "Marine and fishing activity"],
    travel: ["Direct flights via Masset Municipal Airport", "Highway 16 north access", "Nearby Old Massett and Tow Hill/North Beach"],
    services: ["Northern Haida Gwaii Hospital & Health Centre", "Airport", "Fuel and groceries", "Restaurants and visitor services"],
  },
  {
    slug: "old-massett",
    name: "Old Massett",
    description: "Historic Haida community near Masset, known for Haida culture, carving, ocean access and community life.",
    highlights: ["Haida arts and carving", "Community events", "North coast setting"],
    travel: ["Road access from Masset", "Close to North Beach and Tow Hill area"],
    services: ["Community services", "Nearby Masset hospital and airport", "Arts and cultural points of interest"],
  },
  {
    slug: "port-clements",
    name: "Port Clements",
    description: "Central island village with logging history, museum attractions, fishing access and a practical stop between north and south island communities.",
    highlights: ["Golden Spruce Trail", "Port Clements Museum", "Yakoun River access"],
    travel: ["Highway 16 central island access", "Road links to Masset, Tlell and Daajing Giids"],
    services: ["Local services", "Recreation access", "Community facilities"],
  },
  {
    slug: "tlell",
    name: "Tlell",
    description: "Rural east-coast community with beaches, studios, campgrounds, art, agriculture and access to river and beach recreation.",
    highlights: ["East Beach", "Tlell River", "Art studios", "Rural accommodations"],
    travel: ["Highway 16 east coast access", "Between Port Clements and Skidegate/Daajing Giids"],
    services: ["Campgrounds and stays", "Local art and studios", "Outdoor recreation access"],
  },
  {
    slug: "daajing-giids",
    name: "Daajing Giids",
    description: "South island commercial and service hub with restaurants, accommodations, hospital services, harbour access and nearby ferry connections.",
    highlights: ["Harbour", "Restaurants and shops", "Haida Gwaii Hospital and Health Centre", "Nearby Skidegate ferry terminal"],
    travel: ["Road access to Skidegate, Tlell and Sandspit ferry connection", "Close to BC Ferries terminal at Skidegate"],
    services: ["Hospital and health centre", "Food and accommodations", "Marine services", "Government and business services"],
  },
  {
    slug: "skidegate",
    name: "Skidegate",
    description: "Haida community and major arrival point with the Skidegate ferry terminal and the Haida Heritage Centre at Kay Llnagaay nearby.",
    highlights: ["Haida Heritage Centre", "BC Ferries terminal", "Cultural tourism", "Kay Llnagaay"],
    travel: ["BC Ferries terminal for Prince Rupert and Alliford Bay routes", "Road access to Daajing Giids and Tlell"],
    services: ["Ferry access", "Cultural and visitor services", "Community services"],
  },
  {
    slug: "sandspit",
    name: "Sandspit",
    description: "Moresby Island community with K’il Kun Xidgwangs Daanaay Airport, fishing, outdoor access and gateway connections toward Gwaii Haanas.",
    highlights: ["K’il Kun Xidgwangs Daanaay Airport", "Fishing", "Moresby Island access", "Gwaii Haanas staging"],
    travel: ["Flights via Sandspit airport", "Alliford Bay ferry connection to Skidegate", "Moresby Island road access"],
    services: ["Airport", "Accommodation and visitor services", "Outdoor and marine operators"],
  },
]

export const exploreCategories = [
  {
    title: "Travel & Transportation",
    slug: "transportation",
    description: "Ferries, airports, road links, fuel, marine access and travel planning.",
  },
  {
    title: "Food & Drink",
    slug: "food-drink",
    description: "Restaurants, cafes, pubs, groceries and local food stops.",
  },
  {
    title: "Stay",
    slug: "stay",
    description: "Hotels, lodges, cabins, guest houses, campgrounds and RV stays.",
  },
  {
    title: "Things To Do",
    slug: "things-to-do",
    description: "Museums, parks, beaches, hikes, tours, fishing, galleries and cultural experiences.",
  },
  {
    title: "Essential Services",
    slug: "essential-services",
    description: "Hospitals, clinics, emergency services, fuel, hardware, mechanics and practical services.",
  },
  {
    title: "Emergency & Live Info",
    slug: "emergency-live-info",
    description: "Weather, tides, ferry notices, earthquake monitoring, tsunami alerts and preparedness links.",
  },
  {
    title: "Arts, Culture & Heritage",
    slug: "arts-culture-heritage",
    description: "Haida cultural sites, galleries, museums, artists and visitor protocols.",
  },
]

export const directoryEntries = [
  {
    name: "Haida Heritage Centre at Kay Llnagaay",
    category: "Arts, Culture & Heritage",
    community: "Skidegate",
    description: "Major cultural centre and museum sharing Haida history, art, culture and heritage.",
    website: "https://www.haidaheritagecentre.com/visit/",
    phone: "",
    tags: ["Museum", "Culture", "Visitor attraction"],
  },
  {
    name: "Gwaii Haanas National Park Reserve, National Marine Conservation Area Reserve, and Haida Heritage Site",
    category: "Things To Do",
    community: "South Moresby / Gwaii Haanas",
    description: "Protected area in southern Haida Gwaii jointly managed by the Haida Nation and Government of Canada.",
    website: "https://parks.canada.ca/pn-np/bc/gwaiihaanas/visit",
    phone: "",
    tags: ["Parks Canada", "Protected area", "Tours", "Kayaking"],
  },
  {
    name: "BC Ferries — Prince Rupert ↔ Skidegate",
    category: "Travel & Transportation",
    community: "Skidegate",
    description: "Main ferry route connecting Haida Gwaii with Prince Rupert.",
    website: "https://www.bcferries.com/current-conditions",
    phone: "1-888-223-3779",
    tags: ["Ferry", "Travel", "Current conditions"],
  },
  {
    name: "BC Ferries — Skidegate ↔ Alliford Bay",
    category: "Travel & Transportation",
    community: "Skidegate / Alliford Bay",
    description: "Inter-island ferry route between Graham Island and Moresby Island.",
    website: "https://www.bcferries.com/current-conditions",
    phone: "1-888-223-3779",
    tags: ["Ferry", "Moresby Island", "Travel"],
  },
  {
    name: "Masset Municipal Airport",
    category: "Travel & Transportation",
    community: "Masset",
    description: "North island airport serving Masset and northern Haida Gwaii.",
    website: "https://massetbc.com/visitors/airport/",
    phone: "",
    tags: ["Airport", "Flights", "North island"],
  },
  {
    name: "K’il Kun Xidgwangs Daanaay Airport",
    category: "Travel & Transportation",
    community: "Sandspit",
    description: "Transport Canada-operated airport at Sandspit on Moresby Island.",
    website: "https://tc.canada.ca/en/aviation/operating-airports-aerodromes/list-airports-owned-transport-canada/kil-kun-xidgwangs-daanaay-airport",
    phone: "",
    tags: ["Airport", "Sandspit", "Flights"],
  },
  {
    name: "Haida Gwaii Hospital and Health Centre — Xaayda Gwaay Ngaaysdll Naay",
    category: "Essential Services",
    community: "Daajing Giids",
    description: "Hospital and health centre operated by Northern Health in Daajing Giids.",
    website: "https://www.healthlinkbc.ca/find-care/find-health-services/program/haida-gwaii-hospital-and-health-centre-xaayda-gwaay",
    phone: "250-559-4900",
    tags: ["Hospital", "Health", "Emergency"],
  },
  {
    name: "Northern Haida Gwaii Hospital and Health Centre",
    category: "Essential Services",
    community: "Masset",
    description: "Health centre serving Masset, Old Massett, Port Clements and northern Haida Gwaii.",
    website: "https://www.northernhealth.ca/",
    phone: "",
    tags: ["Hospital", "Health", "Emergency"],
  },
  {
    name: "EmergencyInfoBC",
    category: "Emergency & Live Info",
    community: "Haida Gwaii",
    description: "Provincial emergency information and public safety updates.",
    website: "https://www.emergencyinfobc.gov.bc.ca/",
    phone: "",
    tags: ["Emergency", "Alerts", "Preparedness"],
  },
  {
    name: "PreparedBC",
    category: "Emergency & Live Info",
    community: "British Columbia",
    description: "Emergency preparedness guidance for earthquakes, tsunamis, severe weather and disasters.",
    website: "https://www2.gov.bc.ca/gov/content/safety/emergency-management/preparedbc",
    phone: "",
    tags: ["Preparedness", "Emergency", "Safety"],
  },
  {
    name: "Earthquakes Canada — Haida Gwaii Region",
    category: "Emergency & Live Info",
    community: "Haida Gwaii",
    description: "Official regional earthquake monitoring and recent earthquake information.",
    website: "https://earthquakescanada.nrcan.gc.ca/index-en.php?tpl_region=qci",
    phone: "",
    tags: ["Earthquakes", "Seismology", "Alerts"],
  },
  {
    name: "Environment Canada Weather",
    category: "Emergency & Live Info",
    community: "Haida Gwaii",
    description: "Official weather forecasts, warnings and marine weather links.",
    website: "https://weather.gc.ca/",
    phone: "",
    tags: ["Weather", "Warnings", "Marine"],
  },
  {
    name: "Canadian Tide and Current Stations",
    category: "Emergency & Live Info",
    community: "Haida Gwaii",
    description: "Official tide and water level station search for Canadian waters.",
    website: "https://tides.gc.ca/en/stations",
    phone: "",
    tags: ["Tides", "Marine", "Water levels"],
  },
  {
    name: "Go Haida Gwaii Visitor Information",
    category: "Things To Do",
    community: "Haida Gwaii",
    description: "Visitor information and trip planning resource for Haida Gwaii.",
    website: "https://www.gohaidagwaii.ca/visitor-information",
    phone: "",
    tags: ["Visitor info", "Travel planning", "Tourism"],
  },
]

export const emergencyContacts = [
  { label: "Emergency", value: "911", href: "tel:911" },
  { label: "HealthLink BC", value: "811", href: "tel:811" },
  { label: "BC Ferries", value: "1-888-223-3779", href: "tel:18882233779" },
  { label: "EmergencyInfoBC", value: "Provincial emergency updates", href: "https://www.emergencyinfobc.gov.bc.ca/" },
  { label: "PreparedBC", value: "Emergency preparedness", href: "https://www2.gov.bc.ca/gov/content/safety/emergency-management/preparedbc" },
]
