"use client"
import { useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { GripVertical, Plus, Save, Trash2 } from "lucide-react"
import { supabase } from "@/lib/supabase"

type Block = { id:string; type:string; content?:string; url?:string; label?:string; alt?:string; level?:number }
async function authHeaders(): Promise<Record<string,string>> { const { data }=await supabase.auth.getSession(); return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
const blockTypes = ["paragraph","heading","image","quote","callout","button","divider"]

export function PageEditor({ initial }: { initial?: any }){
  const router=useRouter(); const [page,setPage]=useState<any>(initial||{title:"",slug:"",eyebrow:"",description:"",blocks:[],status:"draft",visibility:"public",seo_title:"",seo_description:""}); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(""); const [drag,setDrag]=useState<number|null>(null)
  const publicUrl=useMemo(()=>page.slug?`/pages/${page.slug}`:"",[page.slug])
  function add(type:string){ setPage((p:any)=>({...p,blocks:[...(p.blocks||[]),{id:crypto.randomUUID(),type,content:type==='divider'?'':type==='heading'?'New heading':'New block'}]})) }
  function patchBlock(i:number,patch:any){setPage((p:any)=>({...p,blocks:p.blocks.map((b:any,j:number)=>j===i?{...b,...patch}:b)}))}
  function dropAt(i:number){ if(drag===null||drag===i)return setDrag(null); setPage((p:any)=>{const next=[...p.blocks]; const [item]=next.splice(drag,1); next.splice(i,0,item); return {...p,blocks:next}}); setDrag(null) }
  async function save(){setBusy(true);setMsg(""); const method=initial?.id?'PUT':'POST'; const url=initial?.id?`/api/admin/site-pages/${initial.id}`:'/api/admin/site-pages'; const r=await fetch(url,{method,headers:{...(await authHeaders()),'Content-Type':'application/json'},body:JSON.stringify(page)}); const j=await r.json(); if(!r.ok){setMsg(j.error||'Could not save page.');setBusy(false);return} setMsg('Saved.'); setBusy(false); if(!initial?.id)router.replace(`/admin/pages/${j.page.id}`) }
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-8 sm:px-6"><section className="rounded-3xl border bg-white p-7 shadow-sm"><p className="text-sm font-black uppercase tracking-[.18em] text-hgnBlue">Page Builder</p><h1 className="mt-2 font-serif text-4xl font-bold">{initial?.id?'Edit page':'Create page'}</h1><p className="mt-2 text-slate-600">Drag blocks to reorder them. Publish when you are ready, then add the page to a menu or footer.</p></section>{msg&&<div className="rounded-2xl border bg-white p-4 font-bold">{msg}</div>}
    <section className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-4"><div className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2"><label>Page title<input value={page.title} onChange={e=>setPage({...page,title:e.target.value})}/></label><label>Slug<input value={page.slug} onChange={e=>setPage({...page,slug:e.target.value})} placeholder="about-us"/></label><label>Eyebrow<input value={page.eyebrow||''} onChange={e=>setPage({...page,eyebrow:e.target.value})}/></label><label>Short description<input value={page.description||''} onChange={e=>setPage({...page,description:e.target.value})}/></label></div>
      <div className="space-y-3">{(page.blocks||[]).map((b:Block,i:number)=><div key={b.id} draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>dropAt(i)} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm font-black uppercase tracking-wide text-slate-500"><GripVertical size={18}/>{b.type}</div><button onClick={()=>setPage((p:any)=>({...p,blocks:p.blocks.filter((_:any,j:number)=>j!==i)}))} className="rounded-full border p-2 text-red-700"><Trash2 size={15}/></button></div>{b.type==='divider'?<hr/>:b.type==='image'?<div className="grid gap-2"><input value={b.url||''} onChange={e=>patchBlock(i,{url:e.target.value})} placeholder="Image URL"/><input value={b.alt||''} onChange={e=>patchBlock(i,{alt:e.target.value})} placeholder="Alt text"/></div>:b.type==='button'?<div className="grid gap-2 md:grid-cols-2"><input value={b.label||''} onChange={e=>patchBlock(i,{label:e.target.value})} placeholder="Button label"/><input value={b.url||''} onChange={e=>patchBlock(i,{url:e.target.value})} placeholder="/internal-page or https://website.com"/></div>:<textarea rows={b.type==='paragraph'?5:3} value={b.content||''} onChange={e=>patchBlock(i,{content:e.target.value})}/>}</div>)}</div>
      <div className="rounded-2xl border border-dashed bg-white p-4"><p className="mb-3 text-sm font-black">Add a block</p><div className="flex flex-wrap gap-2">{blockTypes.map(type=><button key={type} onClick={()=>add(type)} className="inline-flex items-center gap-1 rounded-full border px-3 py-2 text-sm font-bold hover:border-hgnBlue"><Plus size={14}/>{type}</button>)}</div></div>
    </div><aside className="space-y-4"><div className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-black">Publishing</h2><label className="mt-3 block">Status<select value={page.status} onChange={e=>setPage({...page,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option></select></label><label className="mt-3 block">Visibility<select value={page.visibility} onChange={e=>setPage({...page,visibility:e.target.value})}><option value="public">Public</option><option value="logged_in">Logged-in readers</option><option value="members">Members</option><option value="staff">Staff only</option><option value="disabled">Disabled</option></select></label>{publicUrl&&<a href={publicUrl} target="_blank" rel="noreferrer" className="mt-4 block text-sm font-bold text-hgnBlue underline">Preview public route</a>}<button disabled={busy} onClick={()=>void save()} className="hgn-btn-primary mt-5 inline-flex w-full items-center justify-center gap-2"><Save size={17}/>{busy?'Saving…':'Save page'}</button></div><div className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-black">Search & sharing</h2><label className="mt-3 block">SEO title<input value={page.seo_title||''} onChange={e=>setPage({...page,seo_title:e.target.value})}/></label><label className="mt-3 block">SEO description<textarea rows={4} value={page.seo_description||''} onChange={e=>setPage({...page,seo_description:e.target.value})}/></label></div></aside></section></main>
}
