import Link from "next/link"

type Race = { place: string; office: string; seats: string; status: "Vote" | "Acclaimed"; candidates: string[]; note?: string; official?: string }
const municipal: Race[] = [
  { place: "Masset", office: "Mayor", seats: "1 seat", status: "Acclaimed", candidates: ["Barry Pages"], note: "Elected by acclamation.", official: "https://www.masset.ca/village-office/2026-municipal-election" },
  { place: "Masset", office: "Council", seats: "4 seats", status: "Vote", candidates: ["Jim Currie", "Jody Grange", "Bret Johnston", "Martin Lewis", "Robert Morton", "Susan Musgrave", "Peter Sloan", "Kate Stichbury"], official: "https://www.masset.ca/village-office/2026-municipal-election" },
  { place: "Port Clements", office: "Mayor", seats: "1 seat", status: "Vote", candidates: ["Scott Cabianca", "Kazamir Falconbridge", "Rob Kidd"], official: "https://portclements.ca/municipal-government/elections/" },
  { place: "Port Clements", office: "Council", seats: "4 seats", status: "Vote", candidates: ["Jasmine Beachy", "Amber Bellis", "Brigid Cumming", "Doris Fischer", "Norman Gould", "Derek Hardt", "Sarah Hunt", "Dale Lore", "Wayne Nicol", "Dennis Reindl", "Betty Stewart"], official: "https://portclements.ca/municipal-government/elections/" },
  { place: "Daajing Giids", office: "Mayor", seats: "1 seat", status: "Vote", candidates: ["Jim LeMottee", "Kris Olsen"], official: "https://daajinggiids.ca/election/" },
  { place: "Daajing Giids", office: "Council", seats: "4 seats", status: "Vote", candidates: ["Bill Beamish", "Kim Claggett", "Alanah Mountifield", "Lisa Pineault", "Jennifer Rutt", "Hayl Zacks"], official: "https://daajinggiids.ca/election/" },
]
const trustees: Race[] = [
  { place: "Area 1 · Old Massett", office: "School trustee", seats: "1 seat", status: "Acclaimed", candidates: ["Wilson Brown"], note: "Elected by acclamation." },
  { place: "Area 2 · North", office: "School trustee", seats: "1 seat", status: "Vote", candidates: ["Ashley Currie", "Tammy Gates"] },
  { place: "Area 3 · Central", office: "School trustee", seats: "1 seat", status: "Vote", candidates: ["Jam Clark", "Jennifer Jury", "Megan Moncrieff", "Kim Nickel"] },
  { place: "Area 4 · Skidegate", office: "School trustee", seats: "1 seat", status: "Acclaimed", candidates: ["Dana Moraes"], note: "Elected by acclamation." },
  { place: "Area 5 · South", office: "School trustee", seats: "1 seat", status: "Vote", candidates: ["Miranda Post", "Lindsay Seegmiller", "Meggan Wood"] },
]

function RaceCard({ race }: { race: Race }) { return <article className="border border-stone-300 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="newspaper-kicker">{race.place}</p><h3 className="mt-1 font-serif text-2xl font-bold">{race.office}</h3><p className="mt-1 text-sm text-stone-600">{race.seats}</p></div><span className={`rounded-full px-3 py-1 text-[11px] font-bold uppercase tracking-wide ${race.status === "Vote" ? "bg-hgnRed text-white" : "bg-stone-200 text-stone-700"}`}>{race.status === "Vote" ? "On the ballot" : "Acclaimed"}</span></div><ul className="mt-4 grid gap-1.5 text-sm leading-6">{race.candidates.map((candidate) => <li key={candidate} className="border-t border-stone-100 pt-1.5">{candidate}</li>)}</ul>{race.note ? <p className="mt-3 text-sm font-bold text-stone-600">{race.note}</p> : null}{race.official ? <a href={race.official} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-bold text-hgnBlue hover:text-hgnRed">Official voting information →</a> : null}</article> }

export default function ElectionPage() { return <main className="newspaper-shell py-7"><header className="border-b border-stone-900 pb-6"><p className="newspaper-kicker text-hgnRed">2026 general local election</p><h1 className="mt-2 max-w-4xl font-serif text-5xl font-bold leading-[.96] tracking-tight sm:text-6xl">Haida Gwaii Election Guide</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-stone-600">A clear guide to the local races, candidates and where to find official voting information.</p></header><section className="my-7 grid gap-4 border-y border-stone-400 py-5 md:grid-cols-3"><div><p className="newspaper-kicker">Voting day</p><p className="mt-1 font-serif text-2xl font-bold">Saturday, Oct. 17, 2026</p></div><div><p className="newspaper-kicker">What is here</p><p className="mt-1 font-serif text-2xl font-bold">Municipal & school trustee races</p></div><div><p className="newspaper-kicker">Important</p><p className="mt-1 text-sm leading-6 text-stone-600">Each local government runs its own election. Check its official page for your voting place, advance voting and mail-ballot details.</p></div></section><section><div className="newspaper-section-heading"><h2>Municipal races</h2></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{municipal.map((race) => <RaceCard key={`${race.place}-${race.office}`} race={race}/>)}</div></section><section className="mt-10"><div className="newspaper-section-heading"><h2>School District 50 trustee races</h2><a href="https://sd50.bc.ca/" target="_blank" rel="noreferrer">School District 50 →</a></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{trustees.map((race) => <RaceCard key={race.place} race={race}/>)}</div></section><section className="mt-10 border-y border-stone-400 py-6"><p className="newspaper-kicker text-hgnRed">Already decided</p><h2 className="mt-2 font-serif text-3xl font-bold">North Coast Regional District</h2><p className="mt-3 max-w-3xl leading-7 text-stone-600">Both directly elected Haida Gwaii positions were decided by acclamation: Johanne Young in Electoral Area D (Rural Graham Island) and Evan Putterill in Electoral Area E (Moresby Island/Sandspit).</p></section><section className="mt-10 border border-stone-300 bg-stone-50 p-6"><p className="newspaper-kicker">HGN reporting</p><h2 className="mt-2 font-serif text-3xl font-bold">Need the full election story?</h2><p className="mt-2 max-w-2xl leading-7 text-stone-600">This guide reflects HGN’s Sept. 24 candidate roundup. We will update election coverage as official local information and results are released.</p><Link href="/articles/who-s-on-the-ballot-haida-gwaii-s-2026-local-election-at-a-glance-58727" className="mt-4 inline-block font-bold text-hgnBlue hover:text-hgnRed">Read the ballot-at-a-glance story →</Link></section></main> }
