import Link from "next/link"
import { createClient } from "@supabase/supabase-js"
import { supabase } from "@/lib/supabase"
import { getArticleImage } from "@/lib/article-images"

export const dynamic = "force-dynamic"

type Race = { id?: string; group_name: string; place: string; office: string; seats?: string | null; ballot_status: "vote" | "acclaimed" | "information"; candidates: string[]; note?: string | null; official_url?: string | null; sort_order?: number }
type Debate = { id: string; day_label: string; event_date?: string | null; school_title: string; school_url?: string | null; school_zoom_url?: string | null; school_status: "upcoming" | "live" | "replay" | "hidden"; municipal_title: string; municipal_url?: string | null; municipal_zoom_url?: string | null; municipal_status: "upcoming" | "live" | "replay" | "hidden"; venue_note?: string | null; sort_order: number }
type Article = { id: string; title: string; slug: string; excerpt?: string | null; image_url?: string | null; featured_image_url?: string | null; published_at?: string | null; category?: string | null }
type CandidateProfile = { id: string; slug: string; candidate_name: string; race_name: string; office: string; community?: string | null; portrait_url?: string | null; statement: string }
type ElectionSettings = { eyebrow: string; title: string; introduction: string; voting_day_label: string; voting_day_value: string; question_url?: string | null; question_label: string; official_voting_url?: string | null; official_voting_label: string; forum_heading?: string | null; forum_summary?: string | null; forum_format?: string | null; featured_article_ids?: string[] | null }

const fallbackRaces: Race[] = [
  { group_name: "Municipal races", place: "Masset", office: "Mayor", seats: "1 seat", ballot_status: "acclaimed", candidates: ["Barry Pages"], note: "Elected by acclamation.", official_url: "https://www.masset.ca/village-office/2026-municipal-election" },
  { group_name: "Municipal races", place: "Masset", office: "Council", seats: "4 seats", ballot_status: "vote", candidates: ["Jim Currie", "Jody Grange", "Bret Johnston", "Martin Lewis", "Robert Morton", "Susan Musgrave", "Peter Sloan", "Kate Stichbury"], official_url: "https://www.masset.ca/village-office/2026-municipal-election" },
  { group_name: "Municipal races", place: "Port Clements", office: "Mayor", seats: "1 seat", ballot_status: "vote", candidates: ["Scott Cabianca", "Kazamir Falconbridge", "Rob Kidd"], official_url: "https://portclements.ca/municipal-government/elections/" },
  { group_name: "Municipal races", place: "Port Clements", office: "Council", seats: "4 seats", ballot_status: "vote", candidates: ["Jasmine Beachy", "Amber Bellis", "Brigid Cumming", "Doris Fischer", "Norman Gould", "Derek Hardt", "Sarah Hunt", "Dale Lore", "Wayne Nicol", "Dennis Reindl", "Betty Stewart"], official_url: "https://portclements.ca/municipal-government/elections/" },
  { group_name: "Municipal races", place: "Daajing Giids", office: "Mayor", seats: "1 seat", ballot_status: "vote", candidates: ["Jim LeMottee", "Kris Olsen"], official_url: "https://daajinggiids.ca/election/" },
  { group_name: "Municipal races", place: "Daajing Giids", office: "Council", seats: "4 seats", ballot_status: "vote", candidates: ["Bill Beamish", "Kim Claggett", "Alanah Mountifield", "Lisa Pineault", "Jennifer Rutt", "Hayl Zacks"], official_url: "https://daajinggiids.ca/election/" },
  { group_name: "School District 50 trustee races", place: "Area 1 · Old Massett", office: "School trustee", seats: "1 seat", ballot_status: "acclaimed", candidates: ["Wilson Brown"], note: "Elected by acclamation." },
  { group_name: "School District 50 trustee races", place: "Area 2 · North", office: "School trustee", seats: "1 seat", ballot_status: "vote", candidates: ["Ashley Currie", "Tammy Gates"] },
  { group_name: "School District 50 trustee races", place: "Area 3 · Central", office: "School trustee", seats: "1 seat", ballot_status: "vote", candidates: ["Jam Clark", "Jennifer Jury", "Megan Moncrieff", "Kim Nickel"] },
  { group_name: "School District 50 trustee races", place: "Area 4 · Skidegate", office: "School trustee", seats: "1 seat", ballot_status: "acclaimed", candidates: ["Dana Moraes"], note: "Elected by acclamation." },
  { group_name: "School District 50 trustee races", place: "Area 5 · South", office: "School trustee", seats: "1 seat", ballot_status: "vote", candidates: ["Miranda Post", "Lindsay Seegmiller", "Meggan Wood"] },
]

function youtubeEmbedUrl(value?: string | null) { if (!value) return null; try { const url = new URL(value); const host = url.hostname.replace(/^www\./, "").toLowerCase(); let id = host === "youtu.be" ? url.pathname.split("/").filter(Boolean)[0] || "" : ""; if (host === "youtube.com" || host === "m.youtube.com") { if (url.pathname === "/watch") id = url.searchParams.get("v") || ""; else id = url.pathname.split("/").filter(Boolean)[1] || "" } return /^[a-zA-Z0-9_-]{6,32}$/.test(id) ? `https://www.youtube-nocookie.com/embed/${id}?rel=0&modestbranding=1` : null } catch { return null } }
function dateLabel(value?: string | null) { return value ? new Intl.DateTimeFormat("en-CA", { weekday: "short", month: "short", day: "numeric" }).format(new Date(value)) : "Date to be announced" }

function electionServerClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !serviceKey) return supabase
  return createClient(url, serviceKey, { auth: { persistSession: false, autoRefreshToken: false } })
}

function DebateCard({ title, youtubeUrl, zoomUrl, status }: { title: string; youtubeUrl?: string | null; zoomUrl?: string | null; status: Debate["school_status"] }) {
  if (status === "hidden") return null
  const embed = youtubeEmbedUrl(youtubeUrl)
  const label = status === "live" ? "Live now" : status === "replay" ? "Watch replay" : "Coming up"
  return <article className="border border-white/20 bg-white/5 p-4"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-red-300">{label}</p><h3 className="mt-1 font-serif text-xl font-bold">{title}</h3>{embed ? <div className="mt-3 aspect-video overflow-hidden bg-black"><iframe src={embed} title={title} className="h-full w-full border-0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div> : !youtubeUrl && !zoomUrl ? <p className="mt-3 text-sm leading-6 text-stone-300">Viewing links will be added here before the forum.</p> : null}<div className="mt-3 flex flex-wrap gap-2">{youtubeUrl ? <a href={youtubeUrl} target="_blank" rel="noreferrer" className="border border-[#f4eee3] bg-[#f4eee3] px-3 py-2 text-sm font-bold text-stone-950">{status === "replay" ? "Watch replay on YouTube" : "Watch on YouTube"} →</a> : null}{zoomUrl && status !== "replay" ? <a href={zoomUrl} target="_blank" rel="noreferrer" className="border border-white/60 px-3 py-2 text-sm font-bold text-white">Join on Zoom →</a> : null}</div></article>
}

function RaceCard({ race }: { race: Race }) { const status = race.ballot_status === "vote" ? "On the ballot" : race.ballot_status === "acclaimed" ? "Acclaimed" : "Information"; return <article className="border border-stone-300 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="newspaper-kicker">{race.place}</p><h3 className="mt-1 font-serif text-2xl font-bold">{race.office}</h3>{race.seats ? <p className="mt-1 text-sm text-stone-600">{race.seats}</p> : null}</div><span className={`rounded-full px-3 py-1 text-[11px] font-bold uppercase tracking-wide ${race.ballot_status === "vote" ? "bg-hgnRed text-white" : "bg-stone-200 text-stone-700"}`}>{status}</span></div><ul className="mt-4 grid gap-1.5 text-sm leading-6">{race.candidates.map((candidate) => <li key={candidate} className="border-t border-stone-100 pt-1.5">{candidate}</li>)}</ul>{race.note ? <p className="mt-3 text-sm font-bold text-stone-600">{race.note}</p> : null}{race.official_url ? <a href={race.official_url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-bold text-hgnBlue hover:text-hgnRed">Official voting information →</a> : null}</article> }

export default async function ElectionPage() {
  // The article choices are publisher-managed. Read them server-side so a public
  // visitor never depends on a separate feature-table RLS policy; the article
  // query below still explicitly limits output to published articles.
  const electionDb = electionServerClient()
  const [{ data: settingsRow }, { data: debateRows }, { data: featureRows }, { data: raceRows }, { data: profileRows }] = await Promise.all([
    supabase.from("hgn_election_settings").select("*").eq("id", "current").maybeSingle(),
    supabase.from("hgn_election_debates").select("*").eq("published", true).order("sort_order").order("event_date"),
    electionDb.from("hgn_election_article_features").select("article_id,sort_order").order("sort_order").limit(8),
    supabase.from("hgn_election_races").select("*").eq("published", true).order("group_name").order("sort_order"),
    supabase.from("hgn_election_candidate_profiles").select("id,slug,candidate_name,race_name,office,community,portrait_url,statement").eq("published", true).order("race_name").order("sort_order").order("candidate_name"),
  ])
  const settings = (settingsRow || { eyebrow: "2026 local election", title: "Haida Gwaii Election Guide", introduction: "Candidates, forums, local news and the information you need before voting.", voting_day_label: "Voting day", voting_day_value: "Saturday, Oct. 17, 2026", question_url: "https://forms.gle/3HfnM7kNYF4nZ2168", question_label: "Submit a question", official_voting_label: "Official voting information", forum_heading: "How the forums work", forum_summary: "Doors open at 5 p.m. The School Trustee forum runs from 5:30 to 6:30 p.m., followed by a half-hour break for mingling and individual conversations. The Municipal forum begins at 7 p.m. and ends at 9 p.m.", forum_format: "Each forum begins with a one-minute introduction from every candidate, followed by a three-minute campaign statement. Public questions submitted in advance are curated to provide a broad range of inquiry. Every candidate answers each question for one to two minutes, with the speaking order rotated. If time permits, questions from the floor may be included. Light refreshments and snacks are available, but a full dinner is not provided." }) as ElectionSettings
  const features = featureRows || []
  const ids = settings.featured_article_ids?.length ? settings.featured_article_ids : features.map((feature: { article_id: string }) => feature.article_id)
  const { data: articleRows } = ids.length ? await electionDb.from("articles").select("id,title,slug,excerpt,image_url,featured_image_url,published_at,category").in("id", ids).eq("status", "published") : { data: [] }
  const byId = new Map(((articleRows || []) as Article[]).map((article) => [article.id, article]))
  const articles = ids.map((id: string) => byId.get(id)).filter(Boolean) as Article[]
  const debates = (debateRows || []) as Debate[]
  const races = (raceRows?.length ? raceRows : fallbackRaces) as Race[]
  const groups = Array.from(new Set(races.map((race) => race.group_name)))
  const profiles = (profileRows || []) as CandidateProfile[]

  return <main className="newspaper-shell py-6 sm:py-8">
    <header className="overflow-hidden bg-[#071f35] px-6 py-8 text-[#f4eee3] sm:px-9 sm:py-11"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-red-300">{settings.eyebrow}</p><h1 className="mt-3 max-w-4xl font-serif text-5xl font-bold leading-[.94] tracking-tight sm:text-6xl">{settings.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-stone-200">{settings.introduction}</p><div className="mt-7 flex flex-wrap gap-3">{settings.question_url ? <a href={settings.question_url} target="_blank" rel="noreferrer" className="border border-[#f4eee3] bg-[#f4eee3] px-4 py-3 text-sm font-bold text-stone-950">{settings.question_label} →</a> : null}{settings.official_voting_url ? <a href={settings.official_voting_url} target="_blank" rel="noreferrer" className="border border-white/60 px-4 py-3 text-sm font-bold">{settings.official_voting_label} →</a> : null}</div></header>
    <section className="grid gap-4 border-b border-stone-400 py-6 md:grid-cols-[.8fr_1.2fr]"><div><p className="newspaper-kicker">{settings.voting_day_label}</p><p className="mt-1 font-serif text-2xl font-bold">{settings.voting_day_value}</p></div><p className="text-sm leading-6 text-stone-600">Follow HGN for candidate information, public forums and local election reporting. Official local-government pages remain the source for voting places, advance voting and mail-ballot details.</p></section>
    <section className="mt-8 border border-stone-300 bg-[#f4eee3] p-5 sm:flex sm:items-center sm:justify-between sm:gap-6"><div><p className="newspaper-kicker text-hgnRed">Candidate information</p><h2 className="mt-1 font-serif text-3xl font-bold">Candidate Profiles</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-700">Read candidate-submitted profiles, grouped by race. {profiles.length ? `${profiles.length} profile${profiles.length === 1 ? "" : "s"} currently available.` : "Profiles are being added."}</p></div><Link href="/election/candidates" className="mt-4 inline-block whitespace-nowrap bg-hgnBlue px-4 py-3 text-sm font-bold text-white hover:bg-hgnRed sm:mt-0">View candidate profiles →</Link></section>
    <section className="mt-9"><p className="text-sm text-stone-600">School trustee forum at 5:30 p.m. · Municipal forum at 7 p.m.</p>{debates.length ? <div className="mt-4 divide-y divide-white/20 bg-[#071f35] text-white">{debates.map((debate) => <section key={debate.id} className="grid gap-4 p-5 md:grid-cols-2"><div className="border-b border-white/20 pb-4 md:col-span-2"><div className="grid gap-3 sm:grid-cols-[minmax(190px,.7fr)_minmax(0,1.3fr)] sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-red-300">{dateLabel(debate.event_date)}</p><h3 className="mt-1 font-serif text-3xl font-bold">{debate.day_label}</h3></div>{debate.venue_note ? <p className="max-w-3xl text-sm leading-6 text-stone-200">{debate.venue_note}</p> : null}</div></div><DebateCard title={debate.school_title} youtubeUrl={debate.school_url} zoomUrl={debate.school_zoom_url} status={debate.school_status}/><DebateCard title={debate.municipal_title} youtubeUrl={debate.municipal_url} zoomUrl={debate.municipal_zoom_url} status={debate.municipal_status}/></section>)}</div> : <div className="mt-4 border border-dashed border-stone-300 bg-stone-50 p-6"><p className="font-serif text-2xl font-bold">Forum schedule coming shortly</p><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600">The HGN editor can add each forum day’s YouTube and Zoom links for both School Trustee and Municipal forums, then choose whether each appears as upcoming, live or replay.</p></div>}</section>
    {(settings.forum_summary || settings.forum_format) ? <section className="mt-8 grid gap-5 border-y border-stone-400 py-7 lg:grid-cols-[.78fr_1.22fr]"><div><p className="newspaper-kicker text-hgnRed">Before you attend</p><h2 className="mt-2 font-serif text-3xl font-bold">{settings.forum_heading || "How the forums work"}</h2></div><div className="grid gap-5 text-sm leading-7 text-stone-700"><p className="whitespace-pre-line">{settings.forum_summary}</p><div className="border-l-4 border-hgnRed pl-4 font-medium whitespace-pre-line">{settings.forum_format}</div></div></section> : null}
    {articles.length ? <section className="mt-10"><div className="newspaper-section-heading"><h2>Election news from HGN</h2><Link href="/articles">All coverage →</Link></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{articles.map((article) => <Link key={article.id} href={`/articles/${article.slug}`} className="group border border-stone-300 bg-white p-3"><div className="aspect-[16/10] bg-stone-100">{getArticleImage(article) ? <img src={getArticleImage(article) || ""} alt="" className="h-full w-full object-cover"/> : null}</div><p className="mt-3 newspaper-kicker">{article.category || "Election"}</p><h3 className="mt-1 font-serif text-xl font-bold leading-tight group-hover:text-hgnRed">{article.title}</h3>{article.excerpt ? <p className="mt-2 line-clamp-3 text-sm leading-6 text-stone-600">{article.excerpt}</p> : null}</Link>)}</div></section> : null}
    {groups.map((group) => <section key={group} className="mt-10"><div className="newspaper-section-heading"><h2>{group}</h2>{group.includes("School") ? <a href="https://sd50.bc.ca/" target="_blank" rel="noreferrer">School District 50 →</a> : null}</div><div className="mt-4 grid gap-4 lg:grid-cols-2">{races.filter((race) => race.group_name === group).map((race) => <RaceCard key={race.id || `${race.place}-${race.office}`} race={race}/>)}</div></section>)}
    <section className="mt-10 border-y border-stone-400 py-6"><p className="newspaper-kicker text-hgnRed">North Coast Regional District</p><h2 className="mt-2 font-serif text-3xl font-bold">Already decided</h2><p className="mt-3 max-w-3xl leading-7 text-stone-600">Both directly elected Haida Gwaii positions were decided by acclamation: Johanne Young in Electoral Area D (Rural Graham Island) and Evan Putterill in Electoral Area E (Moresby Island/Sandspit).</p></section>
  </main>
}
