import Link from "next/link";
import { getEditorWorkbenchSnapshot, workbenchTone, workbenchToneClasses } from "@/lib/editor-workbench";

export const dynamic = "force-dynamic";

export default async function EditorStatusPage() {
  const snapshot = await getEditorWorkbenchSnapshot();
  const signal = snapshot.score >= 75 ? "good" : snapshot.score >= 45 ? "warn" : "bad";
  return <main className="mx-auto max-w-5xl px-4 py-10">
    <div className="rounded-3xl bg-hgnNavy p-8 text-white"><p className="text-sm font-black uppercase tracking-widest text-hgnGold">Two-person beta status</p><h1 className="mt-2 text-5xl font-black">Editor Status</h1><p className="mt-3 max-w-2xl text-white/80">A lightweight readout for you and the editor: what is ready, what is blocked, and whether the homepage has enough shape for the next publishing push.</p><div className="mt-6"><Link href="/admin/editor-workbench" className="rounded-xl bg-white px-5 py-3 font-black text-hgnNavy">Open workbench</Link></div></div>
    <section className="mt-8 grid gap-4 md:grid-cols-4"><div className={`rounded-2xl border p-5 ${workbenchToneClasses(signal)}`}><div className="text-xs font-black uppercase tracking-widest opacity-70">Readiness</div><div className="mt-2 text-4xl font-black">{snapshot.score}%</div></div><div className="rounded-2xl border p-5"><div className="text-xs font-black uppercase tracking-widest text-slate-500">Ready</div><div className="mt-2 text-4xl font-black text-hgnNavy">{snapshot.readyItems.length}</div></div><div className="rounded-2xl border p-5"><div className="text-xs font-black uppercase tracking-widest text-slate-500">Blocked</div><div className="mt-2 text-4xl font-black text-hgnNavy">{snapshot.blockedItems.length}</div></div><div className="rounded-2xl border p-5"><div className="text-xs font-black uppercase tracking-widest text-slate-500">Empty slots</div><div className="mt-2 text-4xl font-black text-hgnNavy">{snapshot.emptySlots.length}</div></div></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="hgn-card p-6"><h2 className="text-2xl font-black text-hgnNavy">Ready or close</h2><div className="mt-4 grid gap-3">{snapshot.items.filter((item) => ["ready_to_publish", "needs_edit", "blocked"].includes(String(item.status))).slice(0, 8).map((item) => <article key={item.id} className={`rounded-xl border p-4 ${workbenchToneClasses(workbenchTone(item.status, item.priority))}`}><div className="text-xs font-black uppercase opacity-70">{item.status} · {item.priority}</div><h3 className="mt-1 font-black">{item.title}</h3><p className="mt-1 text-sm opacity-80">{item.next_step || item.article_slug || "No next step"}</p></article>)}</div></div><div className="hgn-card p-6"><h2 className="text-2xl font-black text-hgnNavy">Homepage shape</h2><div className="mt-4 grid gap-3">{snapshot.slots.slice(0, 8).map((item) => <article key={item.id} className={`rounded-xl border p-4 ${workbenchToneClasses(workbenchTone(item.status))}`}><div className="text-xs font-black uppercase opacity-70">Slot {item.slot_order} · {item.status}</div><h3 className="mt-1 font-black">{item.slot_name}</h3><p className="mt-1 text-sm opacity-80">{item.article_title || item.article_slug || "Empty"}</p></article>)}</div></div></section>
  </main>;
}
