import { NextRequest,NextResponse } from "next/server"
import { createClient } from "@supabase/supabase-js"
const allowed=new Set(["admin","publisher","editor"])
async function clients(req:NextRequest){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,service=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!anon||!service)throw new Error("Supabase server settings are incomplete.");const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/,"");if(!token)throw new Error("Login required.");const auth=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const{data:{user}}=await auth.auth.getUser(token);if(!user)throw new Error("Session could not be verified.");const{data:p}=await auth.from("hgn_profiles").select("account_type,admin_role,is_admin,can_access_publisher_tools").eq("user_id",user.id);if(!(p||[]).some((x:any)=>x.is_admin||x.can_access_publisher_tools||allowed.has(String(x.account_type||"").toLowerCase())||allowed.has(String(x.admin_role||"").toLowerCase())))throw new Error("Publisher or editor access required.");return{db:createClient(url,service,{auth:{persistSession:false}}),user}}
const months="january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|sept|oct|nov|dec"
function text(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim()}
function parseDate(raw:string){const d=new Date(raw);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10)}
function candidates(body:string,start:string,end:string,source:any){const plain=text(body),regex=new RegExp(`([^.!?]{8,110}?)\\s+((${months})\\s+\\d{1,2}(?:,\\s*20\\d{2})?|20\\d{2}-\\d{2}-\\d{2})`,`gi`),out:any[]=[];let m:RegExpExecArray|null;while((m=regex.exec(plain))&&out.length<40){const date=parseDate(m[2]);if(!date||date<start||date>end)continue;const title=m[1].replace(/\s+/g," ").replace(/^[-–|: ]+|[-–|: ]+$/g,"").slice(-100);if(title.length<6)continue;out.push({title,start_date:date,end_date:date,description:`Possible event found on ${source.name}. Review the source and complete missing details before approval.`,community:source.community||null,location:null,source_name:source.name,source_url:source.url,confidence:.55})}return out}
export async function GET(req:NextRequest){try{const{db}=await clients(req);const{data,error}=await db.from("hgn_event_sources").select("*").order("name");if(error)throw error;return NextResponse.json({sources:data||[]})}catch(e:any){return NextResponse.json({error:e.message},{status:e.message.includes("access")?403:400})}}
export async function POST(req:NextRequest){try{const{db,user}=await clients(req);const body=await req.json();if(body.action==="add_source"){const{data,error}=await db.from("hgn_event_sources").insert({name:body.name,url:body.url,community:body.community||null,source_type:body.source_type||"community"}).select().single();if(error)throw error;return NextResponse.json({source:data})}const start=String(body.start_date),end=String(body.end_date);if(!start||!end||end<start)return NextResponse.json({error:"Choose a valid date range."},{status:400});let q=db.from("hgn_event_sources").select("*").eq("active",true);if(Array.isArray(body.source_ids)&&body.source_ids.length)q=q.in("id",body.source_ids);const{data:sources,error}=await q;if(error)throw error;const{data:existing}=await db.from("events").select("title,start_date").gte("start_date",start).lte("start_date",end);const seen=new Set((existing||[]).map((x:any)=>`${String(x.title).toLowerCase().replace(/[^a-z0-9]/g,"")}|${x.start_date}`));let found=0,duplicates=0,failed=0;for(const source of sources||[]){try{const response=await fetch(source.url,{cache:"no-store",headers:{"User-Agent":"HaidaGwaiiNews/1.0 event research"},signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const html=await response.text();for(const c of candidates(html,start,end,source)){const key=`${c.title.toLowerCase().replace(/[^a-z0-9]/g,"")}|${c.start_date}`;if(seen.has(key)){duplicates++;continue}seen.add(key);const{error:insertError}=await db.from("ai_desk_items").insert({item_type:"event",title:c.title,summary:c.description,source_name:c.source_name,source_url:c.source_url,priority:"normal",confidence:c.confidence,agent_name:"AI Desk Event Finder",verification_status:"unverified",dedupe_key:`event-scan:${key}`,payload:{start_date:c.start_date,end_date:c.end_date,community:c.community,location:c.location,scan_range:{start,end}}});if(!insertError)found++}await db.from("hgn_event_sources").update({last_checked_at:new Date().toISOString(),last_status:"success",last_error:null}).eq("id",source.id)}catch(e:any){failed++;await db.from("hgn_event_sources").update({last_checked_at:new Date().toISOString(),last_status:"failed",last_error:e.message}).eq("id",source.id)}}return NextResponse.json({found,duplicates,failed,sources:(sources||[]).length,scanned_by:user.id})}catch(e:any){return NextResponse.json({error:e.message},{status:e.message.includes("access")?403:400})}}
