"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Customer={id:string;business_name:string;default_ad_size:string|null;default_price:number|null;payment_terms:string|null;email:string|null;standing_advertiser:boolean;active:boolean};
const addDays=(date:string,days:number)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const dueFor=(issueDate:string,terms:string|null)=>terms==="net_30"?addDays(issueDate,30):terms==="net_15"?addDays(issueDate,15):issueDate;
export default function StandingBillingPage(){
 const[customers,setCustomers]=useState<Customer[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{void(async()=>{const{data,error}=await supabase.from("hgn_customers").select("id,business_name,default_ad_size,default_price,payment_terms,email,standing_advertiser,active").eq("standing_advertiser",true).eq("active",true).order("business_name");setCustomers((data||[])as Customer[]);setSelected(new Set((data||[]).map(x=>x.id)));setMsg(error?.message||"")})()},[]);
 const total=useMemo(()=>customers.filter(c=>selected.has(c.id)).reduce((s,c)=>s+Number(c.default_price||0),0),[customers,selected]);
 function toggle(id:string){setSelected(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n})}
 async function generate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const issue=String(f.get("issue")||"").trim();const issueDate=String(f.get("issue_date")||"");if(!issue||!issueDate){setMsg("Enter the issue name and print date.");return}const chosen=customers.filter(c=>selected.has(c.id));if(!chosen.length){setMsg("Choose at least one standing advertiser.");return}setBusy(true);const existing=await supabase.from("hgn_billing_items").select("customer_id").eq("issues_covered",issue);const existingIds=new Set((existing.data||[]).map(x=>x.customer_id));const rows=chosen.filter(c=>!existingIds.has(c.id)).map(c=>({customer_id:c.id,billing_period:issueDate.slice(0,7),issues_covered:issue,ad_size:c.default_ad_size,amount:Number(c.default_price||0),due_date:dueFor(issueDate,c.payment_terms),notes:"Created from standing advertiser list."}));if(!rows.length){setBusy(false);setMsg("Those standing advertisers are already in the Billing Queue for this issue.");return}const{error}=await supabase.from("hgn_billing_items").insert(rows);setBusy(false);setMsg(error?.message||`Added ${rows.length} standing advertiser${rows.length===1?"":"s"} to the Billing Queue.`)}
 return <main className="mx-auto max-w-6xl space-y-7 px-6 py-10"><header className="rounded-3xl border bg-white p-8"><p className="text-sm font-black uppercase tracking-widest text-hgnBlue">Friday shortcut</p><h1 className="mt-2 font-serif text-5xl font-bold">Standing Advertisers</h1><p className="mt-3 text-slate-600">Create the next issue&apos;s billing records in one reviewed batch. Nothing is invoiced automatically.</p><div className="mt-5 flex gap-3"><Link href="/admin/billing" className="rounded-full border px-4 py-2 text-sm font-bold">Billing Queue</Link><Link href="/admin/customers" className="rounded-full border px-4 py-2 text-sm font-bold">Customers</Link></div></header>{msg&&<p className="rounded-xl border bg-white p-4 font-bold">{msg}</p>}<form onSubmit={generate} className="space-y-5 rounded-3xl border bg-white p-6"><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-1 font-bold">Issue or edition<input name="issue" required placeholder="July 24, 2026 edition"/></label><label className="grid gap-1 font-bold">Print date<input name="issue_date" required type="date"/></label></div><div className="flex flex-wrap items-center justify-between gap-3 border-y py-4"><div><strong>{selected.size} selected</strong><p className="text-sm text-slate-500">Expected billing value ${total.toFixed(2)}</p></div><div className="flex gap-2"><button type="button" onClick={()=>setSelected(new Set(customers.map(c=>c.id)))} className="rounded-full border px-3 py-2 text-sm font-bold">Select all</button><button type="button" onClick={()=>setSelected(new Set())} className="rounded-full border px-3 py-2 text-sm font-bold">Clear</button></div></div><div className="grid gap-3">{customers.map(c=><label key={c.id} className="flex cursor-pointer items-center justify-between gap-4 rounded-2xl border p-4"><span className="flex items-center gap-3"><input type="checkbox" checked={selected.has(c.id)} onChange={()=>toggle(c.id)}/><span><strong>{c.business_name}</strong><span className="block text-sm text-slate-500">{c.default_ad_size||"No default size"} · {c.payment_terms?.replaceAll("_"," ")||"due on receipt"}</span></span></span><strong>${Number(c.default_price||0).toFixed(2)}</strong></label>)}{!customers.length&&<p className="rounded-xl border border-dashed p-8 text-center text-slate-500">No active standing advertisers yet. Mark them on the Customers page.</p>}</div><button disabled={busy||!customers.length} className="hgn-btn-primary">{busy?"Creating queue...":"Add selected advertisers to Billing Queue"}</button></form></main>}
