"use client";

import Link from "next/link";
import { ChangeEvent, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Row={customer:string;contact:string;email:string;phone:string;billing_period:string;issues:string;ad_size:string;amount:string;invoice_sent:string;invoice_date:string;paid:string;payment_date:string;payment_method:string;notes:string};
const normalize=(s:string)=>s.trim().toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
function parseCsv(text:string){const lines:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===","&&!quoted){row.push(cell);cell="";}else if((ch==="\n"||ch==="\r")&&!quoted){if(ch==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(v=>v.trim()))lines.push(row);row=[];cell="";}else cell+=ch;}row.push(cell);if(row.some(v=>v.trim()))lines.push(row);return lines;}
const truthy=(v:string)=>["yes","true","paid","sent","1","y"].includes(v.trim().toLowerCase());
export default function BillingImportPage(){const[rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const total=useMemo(()=>rows.reduce((s,r)=>s+(Number(r.amount)||0),0),[rows]);async function choose(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const parsed=parseCsv(await file.text());if(parsed.length<2){setMessage("No data rows found.");return;}const headers=parsed[0].map(normalize);const aliases:Record<string,string[]>={customer:["customer","business","business_name","advertiser"],contact:["contact","contact_name"],email:["email"],phone:["phone","telephone"],billing_period:["billing_period","period","edition"],issues:["issues","issue","issues_covered"],ad_size:["ad_size","size"],amount:["amount","price","total"],invoice_sent:["invoice_sent","invoiced","invoice_status"],invoice_date:["invoice_date"],paid:["paid","payment_status"],payment_date:["payment_date","date_paid"],payment_method:["payment_method","method"],notes:["notes","note"]};const idx=(key:string)=>headers.findIndex(h=>aliases[key]?.includes(h));const out=parsed.slice(1).map(cols=>Object.fromEntries(Object.keys(aliases).map(k=>[k,cols[idx(k)]?.trim()||""])) as Row).filter(r=>r.customer);setRows(out);setMessage(`Loaded ${out.length} rows. Review before importing.`);}
 async function run(){setBusy(true);setMessage("Importing...");let imported=0,skipped=0;for(const r of rows){const existing=await supabase.from("hgn_customers").select("id").ilike("business_name",r.customer).limit(1).maybeSingle();let customerId=existing.data?.id;if(!customerId){const created=await supabase.from("hgn_customers").insert({business_name:r.customer,contact_name:r.contact||null,email:r.email||null,phone:r.phone||null,notes:"Imported from Stacey's Google Sheet CSV"}).select("id").single();if(created.error){skipped++;continue;}customerId=created.data.id;}const amount=Number(r.amount)||0;const invoiceStatus=truthy(r.invoice_sent)?"sent":"not_invoiced";const paymentStatus=truthy(r.paid)?"paid":"unpaid";const billing=await supabase.from("hgn_billing_items").insert({customer_id:customerId,billing_period:r.billing_period||null,issues_covered:r.issues||null,ad_size:r.ad_size||null,amount,invoice_status:invoiceStatus,invoice_date:r.invoice_date||null,payment_status:paymentStatus,payment_date:r.payment_date||null,payment_method:r.payment_method||null,notes:r.notes||null}).select("id").single();if(billing.error){skipped++;continue;}if(paymentStatus==="paid"&&amount>0)await supabase.from("hgn_payments").insert({billing_item_id:billing.data.id,customer_id:customerId,amount,payment_date:r.payment_date||new Date().toISOString().slice(0,10),payment_method:r.payment_method||"other",notes:"Imported payment"});imported++;}setBusy(false);setMessage(`Imported ${imported} billing rows. ${skipped?`${skipped} rows could not be imported.`:""}`);}
 return <main className="mx-auto max-w-6xl space-y-7 px-6 py-10"><header className="rounded-3xl border bg-white p-8"><p className="text-sm font-black uppercase tracking-widest text-hgnBlue">Google Sheets bridge</p><h1 className="mt-2 font-serif text-5xl font-bold">Import advertising CSV</h1><p className="mt-3 max-w-3xl text-slate-600">Download Stacey's Google Sheet as CSV, then bring customers, editions, invoice status and payment status into HGN Operations.</p><Link href="/admin/billing" className="mt-5 inline-block font-bold text-hgnBlue">← Back to Billing Queue</Link></header><section className="rounded-3xl border bg-white p-6"><input type="file" accept=".csv,text/csv" onChange={choose}/><p className="mt-3 text-sm text-slate-500">Recognized headings include Customer, Contact, Email, Phone, Billing Period or Edition, Issues, Ad Size, Amount, Invoice Sent, Invoice Date, Paid, Payment Date, Payment Method and Notes.</p></section>{message&&<p className="rounded-xl border bg-white p-4 font-bold">{message}</p>}{rows.length>0&&<><section className="grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-500">Rows</p><strong className="text-3xl">{rows.length}</strong></article><article className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-500">Value</p><strong className="text-3xl">${total.toFixed(2)}</strong></article><article className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-500">Customers</p><strong className="text-3xl">{new Set(rows.map(r=>r.customer.toLowerCase())).size}</strong></article></section><div className="overflow-x-auto rounded-3xl border bg-white"><table className="min-w-full text-sm"><thead><tr className="border-b text-left"><th className="p-4">Customer</th><th className="p-4">Period/issues</th><th className="p-4">Amount</th><th className="p-4">Invoice</th><th className="p-4">Payment</th></tr></thead><tbody>{rows.slice(0,100).map((r,i)=><tr key={`${r.customer}-${i}`} className="border-b"><td className="p-4 font-bold">{r.customer}</td><td className="p-4">{r.billing_period||r.issues||""}</td><td className="p-4">${(Number(r.amount)||0).toFixed(2)}</td><td className="p-4">{truthy(r.invoice_sent)?"Sent":"Not invoiced"}</td><td className="p-4">{truthy(r.paid)?"Paid":"Unpaid"}</td></tr>)}</tbody></table></div><button disabled={busy} onClick={()=>void run()} className="hgn-btn-primary">{busy?"Importing...":`Import ${rows.length} rows`}</button></>}</main>}
