"use client"
import Link from "next/link"
import { FormEvent, useEffect, useMemo, useState } from "react"
import { supabase } from "@/lib/supabase"

type Subscriber={id:string;mailing_name:string;contact_name:string|null;address_line_1:string;address_line_2:string|null;community:string|null;province:string|null;postal_code:string|null;country:string|null;email:string|null;phone:string|null;copies:number;delivery_method:string;rate_type:string;status:string;start_date:string|null;expiry_date:string|null;paid_through:string|null;notes:string|null}
type Location={id:string;name:string;community:string|null;route_name:string|null;regular_copies:number;summer_copies:number|null;winter_copies:number|null;distribution_type:string;active:boolean;notes:string|null}
type Issue={id:string;publication_date:string;issue_name:string|null;issue_number:string|null;copies_printed:number;subscriber_copies:number;office_copies:number;complimentary_copies:number;damaged_unused:number;notes:string|null}
type Run={id:string;issue_id:string;location_id:string;delivered:number;returned:number;notes:string|null}
const today=()=>new Date().toISOString().slice(0,10)
export default function PrintCirculation(){
 const[subscribers,setSubscribers]=useState<Subscriber[]>([]),[locations,setLocations]=useState<Location[]>([]),[issues,setIssues]=useState<Issue[]>([]),[runs,setRuns]=useState<Run[]>([]),[tab,setTab]=useState("dashboard"),[message,setMessage]=useState(""),[query,setQuery]=useState("")
 async function load(){const[s,l,i,r]=await Promise.all([supabase.from("hgn_print_subscribers").select("*").order("mailing_name"),supabase.from("hgn_print_distribution_locations").select("*").order("community").order("name"),supabase.from("hgn_print_issues").select("*").order("publication_date",{ascending:false}),supabase.from("hgn_print_distribution_runs").select("*")]);const err=s.error||l.error||i.error||r.error;setMessage(err?.message||"");setSubscribers((s.data||[])as Subscriber[]);setLocations((l.data||[])as Location[]);setIssues((i.data||[])as Issue[]);setRuns((r.data||[])as Run[])}
 useEffect(()=>{void load()},[])
 const active=subscribers.filter(x=>x.status==="active"),expiring=active.filter(x=>x.expiry_date&&x.expiry_date<=new Date(Date.now()+45*86400000).toISOString().slice(0,10)),latest=issues[0]
 const latestRuns=latest?runs.filter(r=>r.issue_id===latest.id):[],delivered=latestRuns.reduce((s,r)=>s+r.delivered,0),returned=latestRuns.reduce((s,r)=>s+r.returned,0)
 const shownSubscribers=useMemo(()=>subscribers.filter(s=>[s.mailing_name,s.contact_name,s.community,s.postal_code,s.email].join(" ").toLowerCase().includes(query.toLowerCase())),[subscribers,query])
 async function addSubscriber(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from("hgn_print_subscribers").insert({mailing_name:f.get("mailing_name"),contact_name:f.get("contact_name")||null,address_line_1:f.get("address_line_1"),address_line_2:f.get("address_line_2")||null,community:f.get("community")||null,province:f.get("province")||"BC",postal_code:f.get("postal_code")||null,country:f.get("country")||"Canada",email:f.get("email")||null,phone:f.get("phone")||null,copies:Number(f.get("copies")||1),delivery_method:f.get("delivery_method")||"mail",rate_type:f.get("rate_type")||"island",status:"active",start_date:f.get("start_date")||null,expiry_date:f.get("expiry_date")||null,paid_through:f.get("paid_through")||null,notes:f.get("notes")||null});setMessage(error?.message||"Subscriber saved.");if(!error){e.currentTarget.reset();await load()}}
 async function addLocation(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from("hgn_print_distribution_locations").insert({name:f.get("name"),community:f.get("community")||null,route_name:f.get("route_name")||null,regular_copies:Number(f.get("regular_copies")||0),summer_copies:f.get("summer_copies")?Number(f.get("summer_copies")):null,winter_copies:f.get("winter_copies")?Number(f.get("winter_copies")):null,distribution_type:f.get("distribution_type")||"free",notes:f.get("notes")||null});setMessage(error?.message||"Distribution location saved.");if(!error){e.currentTarget.reset();await load()}}
 async function addIssue(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from("hgn_print_issues").insert({publication_date:f.get("publication_date"),issue_name:f.get("issue_name")||null,issue_number:f.get("issue_number")||null,copies_printed:Number(f.get("copies_printed")||0),subscriber_copies:Number(f.get("subscriber_copies")||0),office_copies:Number(f.get("office_copies")||0),complimentary_copies:Number(f.get("complimentary_copies")||0),damaged_unused:Number(f.get("damaged_unused")||0),notes:f.get("notes")||null});setMessage(error?.message||"Issue saved.");if(!error){e.currentTarget.reset();await load()}}
 async function saveRun(issueId:string,locationId:string,deliveredValue:number,returnedValue:number){const{error}=await supabase.from("hgn_print_distribution_runs").upsert({issue_id:issueId,location_id:locationId,delivered:deliveredValue,returned:returnedValue},{onConflict:"issue_id,location_id"});setMessage(error?.message||"Distribution numbers saved.");if(!error)await load()}
 return <main className="mx-auto max-w-7xl space-y-7 px-5 py-9"><header className="rounded-3xl border bg-slate-950 p-8 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-300">Print newspaper operations</p><h1 className="mt-2 font-serif text-5xl font-bold">Print Circulation</h1><p className="mt-3 max-w-3xl text-slate-300">Subscribers, mailing labels, issue counts, delivery locations and returns in one place.</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/admin/print-circulation/labels" className="rounded-full bg-white px-4 py-2 text-sm font-black text-slate-950">Print mailing labels</Link>{["dashboard","subscribers","locations","issues","returns"].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full border px-4 py-2 text-sm font-black ${tab===x?"border-white bg-white text-slate-950":"border-slate-600"}`}>{x.replace(/^./,c=>c.toUpperCase())}</button>)}</div></header>{message&&<p className="rounded-2xl border bg-white p-4 font-bold">{message}</p>}
 {tab==="dashboard"&&<><section className="grid gap-4 md:grid-cols-4">{[["Active subscribers",active.length],["Copies mailed",active.reduce((s,x)=>s+x.copies,0)],["Expiring in 45 days",expiring.length],["Active pickup locations",locations.filter(x=>x.active).length]].map(([a,b])=><div key={String(a)} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-500">{a}</p><strong className="mt-2 block text-4xl">{b}</strong></div>)}</section>{latest&&<section className="rounded-3xl border bg-white p-7"><h2 className="font-serif text-3xl font-bold">Latest issue: {latest.issue_name||latest.publication_date}</h2><div className="mt-5 grid gap-4 sm:grid-cols-4"><Stat label="Printed" value={latest.copies_printed}/><Stat label="Distributed" value={delivered}/><Stat label="Returned" value={returned}/><Stat label="Pickup / sell-through" value={delivered?`${Math.round((delivered-returned)/delivered*100)}%`:"—"}/></div></section>}</>}
 {tab==="subscribers"&&<section className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={addSubscriber} className="grid content-start gap-3 rounded-3xl border bg-white p-6"><h2 className="font-serif text-3xl font-bold">Add subscriber</h2><input required name="mailing_name" placeholder="Mailing name"/><input name="contact_name" placeholder="Contact name, if different"/><input required name="address_line_1" placeholder="Street or PO Box"/><input name="address_line_2" placeholder="Address line 2"/><div className="grid gap-3 sm:grid-cols-3"><input name="community" placeholder="Community"/><input name="province" defaultValue="BC"/><input name="postal_code" placeholder="Postal code"/></div><input name="country" defaultValue="Canada"/><div className="grid gap-3 sm:grid-cols-2"><input name="email" type="email" placeholder="Email"/><input name="phone" placeholder="Phone"/></div><div className="grid gap-3 sm:grid-cols-3"><input name="copies" type="number" min="1" defaultValue="1"/><select name="delivery_method" defaultValue="mail"><option value="mail">Mail</option><option value="pickup">Pickup</option><option value="hand_delivery">Hand delivery</option></select><select name="rate_type" defaultValue="island"><option value="island">Island</option><option value="off_island">Off-island</option><option value="complimentary">Complimentary</option></select></div><div className="grid gap-3 sm:grid-cols-3"><label>Start<input name="start_date" type="date" defaultValue={today()}/></label><label>Expiry<input name="expiry_date" type="date"/></label><label>Paid through<input name="paid_through" type="date"/></label></div><textarea name="notes" rows={3} placeholder="Notes"/><button className="hgn-btn-primary">Save subscriber</button></form><div><input value={query} onChange={e=>setQuery(e.target.value)} className="mb-4 w-full" placeholder="Search subscribers"/><div className="grid gap-3">{shownSubscribers.map(s=><article key={s.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-4"><div><h3 className="font-serif text-2xl font-bold">{s.mailing_name}</h3><p className="text-sm text-slate-600">{s.address_line_1}{s.address_line_2?`, ${s.address_line_2}`:""}<br/>{[s.community,s.province,s.postal_code].filter(Boolean).join(" ")}</p></div><span className="text-sm font-black">{s.copies} copy{s.copies===1?"":"ies"}</span></div><p className="mt-3 text-xs font-black uppercase text-slate-500">{s.status} · {s.rate_type.replaceAll("_"," ")} · expires {s.expiry_date||"not set"}</p></article>)}</div></div></section>}
 {tab==="locations"&&<section className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><form onSubmit={addLocation} className="grid content-start gap-3 rounded-3xl border bg-white p-6"><h2 className="font-serif text-3xl font-bold">Add distribution location</h2><input required name="name" placeholder="Business or pickup location"/><input name="community" placeholder="Community"/><input name="route_name" placeholder="Delivery route"/><div className="grid gap-3 sm:grid-cols-3"><label>Regular<input name="regular_copies" type="number" min="0" defaultValue="0"/></label><label>Summer<input name="summer_copies" type="number" min="0"/></label><label>Winter<input name="winter_copies" type="number" min="0"/></label></div><select name="distribution_type"><option value="free">Free pickup</option><option value="paid">Paid retail</option><option value="consignment">Consignment</option></select><textarea name="notes" rows={3} placeholder="Delivery notes"/><button className="hgn-btn-primary">Save location</button></form><div className="grid gap-3">{locations.map(l=><article key={l.id} className="rounded-2xl border bg-white p-5"><h3 className="font-serif text-2xl font-bold">{l.name}</h3><p className="text-sm text-slate-600">{l.community||"No community"} · {l.route_name||"No route"}</p><p className="mt-2 font-bold">Regular {l.regular_copies} · Summer {l.summer_copies??"—"} · Winter {l.winter_copies??"—"}</p></article>)}</div></section>}
 {tab==="issues"&&<section className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><form onSubmit={addIssue} className="grid content-start gap-3 rounded-3xl border bg-white p-6"><h2 className="font-serif text-3xl font-bold">Add print issue</h2><label>Publication date<input required name="publication_date" type="date" defaultValue={today()}/></label><input name="issue_name" placeholder="Issue name"/><input name="issue_number" placeholder="Issue number"/><div className="grid gap-3 sm:grid-cols-2"><label>Copies printed<input name="copies_printed" type="number" min="0"/></label><label>Subscriber copies<input name="subscriber_copies" type="number" min="0" defaultValue={active.reduce((s,x)=>s+x.copies,0)}/></label><label>Office copies<input name="office_copies" type="number" min="0"/></label><label>Complimentary<input name="complimentary_copies" type="number" min="0"/></label><label>Damaged/unused<input name="damaged_unused" type="number" min="0"/></label></div><textarea name="notes" rows={3}/><button className="hgn-btn-primary">Save issue</button></form><div className="grid gap-3">{issues.map(i=>{const rr=runs.filter(r=>r.issue_id===i.id),d=rr.reduce((s,x)=>s+x.delivered,0),ret=rr.reduce((s,x)=>s+x.returned,0);return <article key={i.id} className="rounded-2xl border bg-white p-5"><h3 className="font-serif text-2xl font-bold">{i.issue_name||i.publication_date}</h3><p className="text-sm text-slate-600">{i.publication_date}{i.issue_number?` · Issue ${i.issue_number}`:""}</p><p className="mt-2 font-bold">Printed {i.copies_printed} · Delivered {d} · Returned {ret} · Pickup {d?Math.round((d-ret)/d*100):0}%</p></article>})}</div></section>}
 {tab==="returns"&&<section className="space-y-5"><div className="rounded-2xl border bg-white p-5"><h2 className="font-serif text-3xl font-bold">Issue delivery and returns</h2><p className="text-slate-600">Enter delivered and returned copies for each location. Pickup is calculated automatically.</p></div>{issues.slice(0,12).map(issue=><IssueRuns key={issue.id} issue={issue} locations={locations} runs={runs} save={saveRun}/>)}</section>}
 </main>
}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase text-slate-500">{label}</p><strong className="mt-1 block text-3xl">{value}</strong></div>}
function IssueRuns({issue,locations,runs,save}:{issue:Issue;locations:Location[];runs:Run[];save:(i:string,l:string,d:number,r:number)=>Promise<void>}){return <section className="rounded-3xl border bg-white p-6"><h3 className="font-serif text-2xl font-bold">{issue.issue_name||issue.publication_date}</h3><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Location</th><th className="p-2">Delivered</th><th className="p-2">Returned</th><th className="p-2">Pickup</th><th className="p-2"></th></tr></thead><tbody>{locations.filter(x=>x.active).map(l=>{const row=runs.find(r=>r.issue_id===issue.id&&r.location_id===l.id);return <RunRow key={l.id} issue={issue.id} location={l} row={row} save={save}/>})}</tbody></table></div></section>}
function RunRow({issue,location,row,save}:{issue:string;location:Location;row?:Run;save:(i:string,l:string,d:number,r:number)=>Promise<void>}){const[d,setD]=useState(row?.delivered??location.regular_copies),[r,setR]=useState(row?.returned??0);return <tr className="border-b"><td className="p-2"><strong>{location.name}</strong><br/><span className="text-xs text-slate-500">{location.community}</span></td><td className="p-2"><input className="w-24" type="number" min="0" value={d} onChange={e=>setD(Number(e.target.value))}/></td><td className="p-2"><input className="w-24" type="number" min="0" max={d} value={r} onChange={e=>setR(Number(e.target.value))}/></td><td className="p-2 font-bold">{d?Math.round((d-r)/d*100):0}%</td><td className="p-2"><button onClick={()=>void save(issue,location.id,d,r)} className="rounded-full border px-3 py-2 font-bold">Save</button></td></tr>}
