"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type ExternalTx = {provider:string;external_id:string;transaction_date:string|null;payer_name:string|null;payer_email:string|null;transaction_type:string|null;status:string|null;description:string|null;gross_amount:number|string;fee_amount:number|string;net_amount:number|string;currency:string|null};
type Order = {square_order_id:string;square_customer_id:string|null;created_at_square:string|null;closed_at_square:string|null;state:string|null;total_amount:number|string;total_tax:number|string;total_discount:number|string;currency:string|null;description:string|null};
type Invoice = {square_invoice_id:string;square_customer_id:string|null;invoice_number:string|null;title:string|null;status:string|null;invoice_date:string|null;due_date:string|null;amount_requested:number|string;currency:string|null};
type Billing = {id:string;billing_period:string|null;issues_covered:string|null;invoice_number:string|null;invoice_status:string;payment_status:string;amount:number|string;due_date:string|null;hgn_customers:{business_name:string}|null;hgn_payments:{amount:number|string;payment_date:string;method:string|null;reference:string|null}[]};

const money=(n:number)=>new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format(n);
const q=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;
function download(name:string, headers:string[], rows:unknown[][]){const csv=[headers.map(q).join(","),...rows.map(r=>r.map(q).join(","))].join("\r\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}

export default function ReportsPage(){
 const [start,setStart]=useState(()=>`${new Date().getFullYear()}-01-01`),[end,setEnd]=useState(()=>new Date().toISOString().slice(0,10));
 const [tx,setTx]=useState<ExternalTx[]>([]),[orders,setOrders]=useState<Order[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[billing,setBilling]=useState<Billing[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setMessage("");const from=`${start}T00:00:00`,to=`${end}T23:59:59`;const [t,o,i,b]=await Promise.all([
   supabase.from("hgn_external_transactions").select("provider,external_id,transaction_date,payer_name,payer_email,transaction_type,status,description,gross_amount,fee_amount,net_amount,currency").gte("transaction_date",from).lte("transaction_date",to).order("transaction_date"),
   supabase.from("hgn_square_orders").select("square_order_id,square_customer_id,created_at_square,closed_at_square,state,total_amount,total_tax,total_discount,currency,description").gte("created_at_square",from).lte("created_at_square",to).order("created_at_square"),
   supabase.from("hgn_square_invoices").select("square_invoice_id,square_customer_id,invoice_number,title,status,invoice_date,due_date,amount_requested,currency").gte("invoice_date",start).lte("invoice_date",end).order("invoice_date"),
   supabase.from("hgn_billing_items").select("id,billing_period,issues_covered,invoice_number,invoice_status,payment_status,amount,due_date,hgn_customers(business_name),hgn_payments(amount,payment_date,method,reference)").order("due_date")
 ]);const err=t.error||o.error||i.error||b.error;if(err)setMessage(err.message);setTx((t.data||[]) as ExternalTx[]);setOrders((o.data||[]) as Order[]);setInvoices((i.data||[]) as Invoice[]);setBilling((b.data||[]) as unknown as Billing[]);setBusy(false)}
 useEffect(()=>{void load()},[]);
 const stats=useMemo(()=>{const gross=tx.reduce((s,r)=>s+Number(r.gross_amount||0),0),fees=tx.reduce((s,r)=>s+Number(r.fee_amount||0),0),net=tx.reduce((s,r)=>s+Number(r.net_amount||0),0),tax=orders.reduce((s,r)=>s+Number(r.total_tax||0),0);const payments=billing.flatMap(x=>x.hgn_payments||[]).filter(p=>p.payment_date>=start&&p.payment_date<=end).reduce((s,p)=>s+Number(p.amount||0),0);const outstanding=billing.reduce((s,x)=>s+Math.max(0,Number(x.amount||0)-(x.hgn_payments||[]).reduce((p,a)=>p+Number(a.amount||0),0)),0);return{gross,fees,net,tax,payments,outstanding}},[tx,orders,billing,start,end]);
 const monthly=useMemo(()=>{const m=new Map<string,{gross:number;fees:number;net:number;count:number}>();tx.forEach(r=>{const key=(r.transaction_date||"").slice(0,7)||"Unknown";const x=m.get(key)||{gross:0,fees:0,net:0,count:0};x.gross+=Number(r.gross_amount||0);x.fees+=Number(r.fee_amount||0);x.net+=Number(r.net_amount||0);x.count++;m.set(key,x)});return [...m.entries()].sort().map(([month,v])=>({month,...v}))},[tx]);
 const outstanding=useMemo(()=>billing.map(x=>{const paid=(x.hgn_payments||[]).reduce((s,p)=>s+Number(p.amount||0),0);return{...x,paid,balance:Math.max(0,Number(x.amount||0)-paid)}}).filter(x=>x.balance>0),[billing]);
 return <main className="mx-auto max-w-7xl space-y-7 px-5 py-9"><header className="rounded-3xl border bg-white p-7"><p className="text-xs font-black uppercase tracking-[.2em] text-hgnBlue">Finance and filing support</p><h1 className="mt-2 font-serif text-5xl font-bold">Reports & Exports</h1><p className="mt-3 max-w-3xl text-slate-600">Turn Square, PayPal, Patreon and HGN billing records into clean working files for bookkeeping, tax preparation, grant reporting and government filings. These are operational exports, not filed tax returns.</p><Link href="/admin/operations" className="mt-5 inline-block font-bold text-hgnBlue">← Back to Operations</Link></header>
 <section className="rounded-3xl border bg-white p-6"><div className="grid gap-4 sm:grid-cols-[1fr_1fr_auto]"><label className="grid gap-1 font-bold">From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="grid gap-1 font-bold">Through<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><button onClick={()=>void load()} disabled={busy} className="hgn-btn-primary self-end">{busy?"Loading…":"Refresh report"}</button></div>{message&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-red-800">{message}</p>}</section>
 <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["External gross",stats.gross],["Processing fees",stats.fees],["External net",stats.net],["Square tax captured",stats.tax],["HGN payments recorded",stats.payments],["Outstanding balance",stats.outstanding]].map(([l,v])=><article key={String(l)} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase tracking-widest text-slate-500">{l}</p><strong className="mt-2 block text-3xl">{money(Number(v))}</strong></article>)}</section>
 <section className="grid gap-5 lg:grid-cols-2">
  <article className="rounded-3xl border bg-white p-6"><h2 className="font-serif text-3xl font-bold">Bookkeeping exports</h2><p className="mt-2 text-sm text-slate-600">Download the detailed source records your accountant can sort and reconcile.</p><div className="mt-5 grid gap-3">
   <button className="rounded-xl border p-4 text-left font-bold hover:border-hgnBlue" onClick={()=>download(`hgn-transaction-ledger-${start}-to-${end}.csv`,["Provider","External ID","Date","Payer","Email","Type","Status","Description","Gross","Fee","Net","Currency"],tx.map(r=>[r.provider,r.external_id,r.transaction_date,r.payer_name,r.payer_email,r.transaction_type,r.status,r.description,r.gross_amount,r.fee_amount,r.net_amount,r.currency]))}>Export transaction ledger ({tx.length})</button>
   <button className="rounded-xl border p-4 text-left font-bold hover:border-hgnBlue" onClick={()=>download(`hgn-square-orders-tax-${start}-to-${end}.csv`,["Order ID","Customer ID","Created","Closed","State","Total","Tax","Discount","Currency","Description"],orders.map(r=>[r.square_order_id,r.square_customer_id,r.created_at_square,r.closed_at_square,r.state,r.total_amount,r.total_tax,r.total_discount,r.currency,r.description]))}>Export Square orders and tax ({orders.length})</button>
   <button className="rounded-xl border p-4 text-left font-bold hover:border-hgnBlue" onClick={()=>download(`hgn-square-invoices-${start}-to-${end}.csv`,["Invoice ID","Customer ID","Invoice Number","Title","Status","Invoice Date","Due Date","Amount","Currency"],invoices.map(r=>[r.square_invoice_id,r.square_customer_id,r.invoice_number,r.title,r.status,r.invoice_date,r.due_date,r.amount_requested,r.currency]))}>Export Square invoices ({invoices.length})</button>
   <button className="rounded-xl border p-4 text-left font-bold hover:border-hgnBlue" onClick={()=>download(`hgn-outstanding-invoices-${end}.csv`,["Customer","Invoice Number","Period","Issues","Due Date","Invoice Status","Payment Status","Amount","Paid","Balance"],outstanding.map(r=>[r.hgn_customers?.business_name||"Unknown",r.invoice_number,r.billing_period,r.issues_covered,r.due_date,r.invoice_status,r.payment_status,r.amount,r.paid,r.balance]))}>Export outstanding invoices ({outstanding.length})</button>
  </div></article>
  <article className="rounded-3xl border bg-white p-6"><h2 className="font-serif text-3xl font-bold">Monthly summary</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Month</th><th>Transactions</th><th>Gross</th><th>Fees</th><th>Net</th></tr></thead><tbody>{monthly.map(r=><tr key={r.month} className="border-b"><td className="py-2 font-bold">{r.month}</td><td>{r.count}</td><td>{money(r.gross)}</td><td>{money(r.fees)}</td><td>{money(r.net)}</td></tr>)}</tbody></table></div><button className="mt-5 rounded-xl border px-4 py-3 font-bold" onClick={()=>download(`hgn-monthly-summary-${start}-to-${end}.csv`,["Month","Transactions","Gross","Fees","Net"],monthly.map(r=>[r.month,r.count,r.gross,r.fees,r.net]))}>Export monthly summary</button><p className="mt-4 text-xs leading-5 text-slate-500">Square tax is reported from order records and should be reconciled with your accountant before GST/PST or corporate filings.</p></article>
 </section></main>
}
