import Link from "next/link";
import { dailyTone, dailyToneClasses, getDailyCommandSnapshot } from "@/lib/daily-command";

export const dynamic = "force-dynamic";

export default async function OperatorStatusPage() {
  const snapshot = await getDailyCommandSnapshot();
  const run = snapshot.activeRun;
  const signal = snapshot.score >= 75 ? "good" : snapshot.score >= 50 ? "warn" : "bad";
  return <main className="mx-auto max-w-5xl px-4 py-10">
    <div className="rounded-3xl bg-hgnNavy p-8 text-white"><p className="text-sm font-black uppercase tracking-widest text-hgnGold">Founder + editor beta</p><h1 className="mt-2 text-5xl font-black">Operator Status</h1><p className="mt-3 max-w-2xl text-white/80">A simple read-only daily snapshot for the two people actually testing HGN right now.</p><div className="mt-6 flex flex-wrap gap-2"><Link href="/admin/daily-command" className="rounded-xl bg-white px-5 py-3 font-black text-hgnNavy">Open daily command</Link><Link href="/admin/editor-workbench" className="rounded-xl bg-hgnGold px-5 py-3 font-black text-hgnNavy">Editor workbench</Link></div></div>
    <section className="mt-8 grid gap-4 md:grid-cols-4"><div className={`rounded-2xl border p-5 ${dailyToneClasses(signal)}`}><div className="text-xs font-black uppercase tracking-widest opacity-70">Readiness</div><div className="mt-2 text-4xl font-black">{snapshot.score}%</div></div><div className="rounded-2xl border p-5"><div className="text-xs font-black uppercase tracking-widest text-slate-500">Open tasks</div><div className="mt-2 text-4xl font-black text-hgnNavy">{snapshot.openTasks.length}</div></div><div className="rounded-2xl border p-5"><div className="text-xs font-black uppercase tracking-widest text-slate-500">Blocked</div><div className="mt-2 text-4xl font-black text-hgnNavy">{snapshot.blockedTasks.length}</div></div><div className="rounded-2xl border p-5"><div className="text-xs font-black uppercase tracking-widest text-slate-500">Handoffs</div><div className="mt-2 text-4xl font-black text-hgnNavy">{snapshot.openHandoffs.length}</div></div></section>
    {run && <section className="mt-8 rounded-2xl border bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-widest text-hgnBlue">{run.run_date} · {run.status}</p><h2 className="mt-1 text-3xl font-black text-hgnNavy">{run.shift_label}</h2><div className="mt-4 grid gap-3 text-sm md:grid-cols-3"><p><b>Publishing:</b> {run.publishing_goal || "Not set"}</p><p><b>Homepage:</b> {run.homepage_goal || "Not set"}</p><p><b>Newsletter/social:</b> {run.newsletter_goal || "Only if useful"}</p></div></section>}
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="hgn-card p-6"><h2 className="text-2xl font-black text-hgnNavy">Today&apos;s must-do list</h2><div className="mt-4 grid gap-3">{snapshot.openTasks.slice(0, 8).map((task) => <article key={task.id} className={`rounded-xl border p-4 ${dailyToneClasses(dailyTone(task.status, task.priority))}`}><div className="text-xs font-black uppercase opacity-70">{task.task_area} · {task.priority} · {task.status}</div><h3 className="mt-1 font-black">{task.task_title}</h3><p className="mt-1 text-sm opacity-80">{task.next_step || task.owner || "No next step"}</p></article>)}</div></div><div className="hgn-card p-6"><h2 className="text-2xl font-black text-hgnNavy">Homepage/story focus</h2><div className="mt-4 grid gap-3">{snapshot.slots.slice(0, 8).map((slot) => <article key={slot.id} className={`rounded-xl border p-4 ${dailyToneClasses(dailyTone(slot.status))}`}><div className="text-xs font-black uppercase opacity-70">Slot {slot.slot_order} · {slot.status}</div><h3 className="mt-1 font-black">{slot.slot_name}</h3><p className="mt-1 text-sm opacity-80">{slot.story_title || slot.article_slug || "Not filled yet"}</p></article>)}</div></div></section>
  </main>;
}
