"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import type { GuidePlace } from "@/lib/guide-places"

const markerStyle: Record<string, { short: string; colour: string }> = { Beach: { short: "B", colour: "#0f6b86" }, Fuel: { short: "F", colour: "#9c3d21" }, Food: { short: "E", colour: "#8a5014" }, "Essential Service": { short: "+", colour: "#9d2635" }, Transportation: { short: "T", colour: "#193f69" }, Culture: { short: "C", colour: "#5b3b76" }, Campground: { short: "C", colour: "#3e6b39" }, Viewpoint: { short: "V", colour: "#73551b" }, "Rest Stop": { short: "R", colour: "#52606d" }, Camera: { short: "L", colour: "#4c6079" } }
const radians = (n: number) => n * Math.PI / 180
function distanceKm(a: { lat: number; lng: number }, b: { latitude: number; longitude: number }) { const R = 6371, dLat = radians(b.latitude - a.lat), dLng = radians(b.longitude - a.lng); const x = Math.sin(dLat / 2) ** 2 + Math.cos(radians(a.lat)) * Math.cos(radians(b.latitude)) * Math.sin(dLng / 2) ** 2; return 2 * R * Math.asin(Math.sqrt(x)) }
function isMappable(place: GuidePlace) { return place.category !== "Camera" && Number.isFinite(place.latitude) && Number.isFinite(place.longitude) && Boolean(place.latitude) && Boolean(place.longitude) }

export default function IslandGuideMap({ places, initialCategory = "All" }: { places: GuidePlace[]; initialCategory?: string }) {
  const mapEl = useRef<HTMLDivElement | null>(null), mapRef = useRef<any>(null), layerRef = useRef<any>(null)
  const [ready, setReady] = useState(false), [category, setCategory] = useState(initialCategory), [query, setQuery] = useState(""), [selected, setSelected] = useState<GuidePlace | null>(null), [location, setLocation] = useState<{ lat: number; lng: number } | null>(null), [locating, setLocating] = useState(false)
  const mappable = useMemo(() => places.filter(isMappable), [places])
  const categories = useMemo(() => ["All", ...Array.from(new Set(mappable.map((place) => place.category)))], [mappable])
  const filtered = useMemo(() => mappable.filter((place) => { if (category !== "All" && place.category !== category) return false; const haystack = `${place.name} ${place.community} ${place.category} ${place.description} ${(place.amenities || []).join(" ")}`.toLowerCase(); return !query.trim() || haystack.includes(query.toLowerCase().trim()) }).sort((a, b) => location ? distanceKm(location, a) - distanceKm(location, b) : Number(Boolean(b.featured)) - Number(Boolean(a.featured))), [mappable, category, query, location])

  useEffect(() => { let cancelled = false; async function load() { if (!mapEl.current || mapRef.current) return; const L = await import("leaflet"); if (cancelled || !mapEl.current) return; const map = L.map(mapEl.current, { scrollWheelZoom: false, zoomControl: true, attributionControl: true }).setView([53.62, -132.02], 8); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: "© OpenStreetMap contributors", maxZoom: 18 }).addTo(map); mapRef.current = map; layerRef.current = L.layerGroup().addTo(map); setReady(true); requestAnimationFrame(() => map.invalidateSize()) } void load(); return () => { cancelled = true; mapRef.current?.remove(); mapRef.current = null; layerRef.current = null; setReady(false) } }, [])
  useEffect(() => { async function draw() { if (!ready || !mapRef.current || !layerRef.current) return; const L = await import("leaflet"); layerRef.current.clearLayers(); filtered.forEach((place) => { const style = markerStyle[place.category] || { short: "•", colour: "#193f69" }; const size = 36; const html = `<div aria-label="${place.name.replace(/"/g, "&quot;")}" style="width:${size}px;height:${size}px;border-radius:50% 50% 50% 7px;background:${style.colour};border:3px solid #fffdf8;color:#fff;display:flex;align-items:center;justify-content:center;font-family:Arial,sans-serif;font-weight:800;font-size:${style.short === "+" ? 23 : 14}px;box-shadow:0 3px 12px rgba(15,23,42,.38);transform:rotate(-45deg)"><span style="transform:rotate(45deg)">${style.short}</span></div>`; const marker = L.marker([place.latitude, place.longitude], { icon: L.divIcon({ html, className: "hgn-guide-map-marker", iconSize: [size, size], iconAnchor: [size / 2, size] }) }); marker.bindTooltip(place.name, { direction: "top", offset: [0, -size / 2], opacity: .94 }); marker.on("click", () => { setSelected(place); mapRef.current?.setView([place.latitude, place.longitude], Math.max(mapRef.current.getZoom(), 11)) }); marker.addTo(layerRef.current) }); if (location) L.circleMarker([location.lat, location.lng], { radius: 8, color: "#fff", fillColor: "#0b6d89", fillOpacity: 1, weight: 3 }).bindTooltip("You are here").addTo(layerRef.current); if (filtered.length) { const bounds = L.latLngBounds(filtered.map((place) => [place.latitude, place.longitude] as [number, number])); mapRef.current.fitBounds(bounds.pad(.16), { maxZoom: 11 }) } } void draw() }, [ready, filtered, location])
  function findMe() { if (!navigator.geolocation) return; setLocating(true); navigator.geolocation.getCurrentPosition((position) => { setLocation({ lat: position.coords.latitude, lng: position.coords.longitude }); setLocating(false) }, () => setLocating(false), { enableHighAccuracy: true, timeout: 10000 }) }
  function reset() { setCategory("All"); setQuery(""); setLocation(null); setSelected(null) }
  function choose(place: GuidePlace) { setSelected(place); mapRef.current?.setView([place.latitude, place.longitude], 12) }
  const hasFilters = category !== "All" || Boolean(query) || Boolean(location)
  return <div className="grid gap-5 lg:grid-cols-[1.45fr_.75fr]">
    <div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="grid gap-3 border-b p-4 md:grid-cols-[minmax(0,1fr)_180px_auto_auto]"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search places and services" className="min-w-0 rounded-xl border px-4 py-3" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-xl border px-4 py-3">{categories.map((item) => <option key={item}>{item}</option>)}</select><button onClick={findMe} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white">{locating ? "Finding…" : "Near me"}</button>{hasFilters ? <button onClick={reset} className="rounded-xl border px-4 py-3 text-sm font-black">Reset</button> : null}</div><div className="flex flex-wrap gap-x-4 gap-y-2 border-b bg-stone-50 px-4 py-3 text-xs font-semibold text-slate-600"><span><b className="text-slate-950">{filtered.length}</b> mapped places</span><span>Tap a pin or result for details</span><span>Live cameras belong in Island Cams, not on this map</span></div><div ref={mapEl} className="h-[52vh] min-h-[380px] w-full md:h-[58vh] md:min-h-[460px]" aria-label="Interactive Haida Gwaii guide map" /></div>
    <aside className="space-y-4">{selected ? <article className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.16em] text-hgnBlue">{selected.category} · {selected.community}</p><h2 className="mt-2 text-2xl font-black">{selected.name}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{selected.description}</p>{selected.address ? <p className="mt-3 text-sm"><strong>Address:</strong> {selected.address}</p> : null}{selected.hours ? <p className="mt-2 text-sm"><strong>Hours:</strong> {selected.hours}</p> : null}{selected.phone ? <a href={`tel:${selected.phone}`} className="mt-2 block text-sm font-bold text-hgnBlue">Call {selected.phone}</a> : null}{selected.caution ? <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-900">{selected.caution}</p> : null}{selected.verifiedAt ? <p className="mt-4 text-xs font-semibold text-slate-500">Last verified {new Intl.DateTimeFormat("en-CA", { dateStyle: "medium" }).format(new Date(selected.verifiedAt))}</p> : null}<div className="mt-4 flex flex-wrap gap-2">{(selected.amenities || []).map((item) => <span key={item} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{item}</span>)}</div><div className="mt-5 flex flex-wrap gap-3"><a href={`https://www.google.com/maps/dir/?api=1&destination=${selected.latitude},${selected.longitude}`} target="_blank" rel="noreferrer" className="rounded-full bg-slate-950 px-4 py-2 text-sm font-bold text-white">Directions</a>{selected.website ? <a href={selected.website} target="_blank" rel="noreferrer" className="rounded-full border px-4 py-2 text-sm font-bold">Official source</a> : null}</div></article> : <div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Find your way around</h2><p className="mt-2 text-sm leading-6 text-slate-600">The map is for physical places. Select a pin or result to see directions, contact details and verified notes.</p></div>}<div className="max-h-[390px] space-y-1 overflow-auto rounded-3xl border bg-white p-3 shadow-sm">{filtered.map((place) => <button key={place.id} onClick={() => choose(place)} className={`w-full rounded-2xl p-3 text-left ${selected?.id === place.id ? "bg-hgnBlue/10" : "hover:bg-slate-50"}`}><span className="text-xs font-black uppercase tracking-wide text-hgnBlue">{place.category}</span><span className="mt-1 block font-black">{place.name}</span><span className="text-xs text-slate-500">{place.community}{location ? ` · ${distanceKm(location, place).toFixed(1)} km away` : ""}</span></button>)}{!filtered.length ? <p className="p-5 text-sm text-slate-500">No matching mapped places. Try resetting the filters.</p> : null}</div></aside>
  </div>
}
