"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Lead={id:string;business_name:string;contact_name:string|null;email:string|null;phone:string|null;stage:string;estimated_value:number|null;last_contact_at:string|null;next_follow_up:string|null;source:string|null;notes:string|null};
const stages=["new","contacted","interested","quote_sent","booked","not_now","closed"];

export default function SalesPage(){
 const[rows,setRows]=useState<Lead[]>([]),[msg,setMsg]=useState("");
 async function load(){const{data,error}=await supabase.from("hgn_sales_leads").select("*").order("next_follow_up",{ascending:true,nullsFirst:false});setRows((data||[])as Lead[]);setMsg(error?.message||"")}
 useEffect(()=>{void load()},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from("hgn_sales_leads").insert({business_name:f.get("business_name"),contact_name:f.get("contact_name")||null,email:f.get("email")||null,phone:f.get("phone")||null,source:f.get("source")||null,estimated_value:f.get("estimated_value")?Number(f.get("estimated_value")):null,next_follow_up:f.get("next_follow_up")||null,notes:f.get("notes")||null});if(error)setMsg(error.message);else{e.currentTarget.reset();void load()}}
 async function stage(id:string,value:string){const patch:Record<string,unknown>={stage:value,updated_at:new Date().toISOString()};if(["contacted","interested","quote_sent"].includes(value))patch.last_contact_at=new Date().toISOString();const{error}=await supabase.from("hgn_sales_leads").update(patch).eq("id",id);if(error)setMsg(error.message);else void load()}
 async function prepareDraft(lead:Lead,kind:"followup"|"renewal"){
   const title=kind==="renewal"?`Renewal outreach: ${lead.business_name}`:`Sales follow-up: ${lead.business_name}`;
   const summary=[`Draft a friendly ${kind==="renewal"?"advertising renewal":"advertising follow-up"} message for ${lead.business_name}.`,lead.contact_name?`Contact: ${lead.contact_name}.`:"",lead.notes?`Context: ${lead.notes}`:"",lead.estimated_value?`Potential value: $${Number(lead.estimated_value).toFixed(2)}.`:""].filter(Boolean).join("\n");
   const{error}=await supabase.from("ai_desk_items").upsert({title,item_type:kind==="renewal"?"renewal":"sales_lead",status:"pending",priority:lead.next_follow_up&&lead.next_follow_up<=new Date().toISOString().slice(0,10)?"high":"normal",summary,proposed_action:"Review and personalize the draft before contacting the customer. Nothing should be sent automatically.",source_name:"HGN Sales Desk",agent_name:"Sales Agent",dedupe_key:`sales:${lead.id}:${kind}`},{onConflict:"dedupe_key"});
   setMsg(error?error.message:`${kind==="renewal"?"Renewal":"Follow-up"} draft added to the AI Desk.`)
 }
 const today=new Date().toISOString().slice(0,10);
 const due=useMemo(()=>rows.filter(r=>!['booked','closed'].includes(r.stage)&&r.next_follow_up&&r.next_follow_up<=today),[rows,today]);
 const active=useMemo(()=>rows.filter(r=>!['closed'].includes(r.stage)),[rows]);
 const pipeline=useMemo(()=>active.reduce((sum,r)=>sum+Number(r.estimated_value||0),0),[active]);
 return <main className="mx-auto max-w-7xl space-y-7 px-6 py-10"><header className="rounded-3xl border bg-white p-8"><p className="text-sm font-black uppercase tracking-widest text-hgnBlue">Advertising growth</p><h1 className="mt-2 font-serif text-5xl font-bold">Sales Desk</h1><p className="mt-2 text-slate-600">A simple worklist for leads, renewals and advertisers worth contacting again. AI drafts stay human-reviewed.</p><div className="mt-5 flex gap-4"><Link href="/admin/ai-desk" className="font-bold text-hgnBlue">Open AI Desk →</Link><Link href="/admin/customers" className="font-bold text-hgnBlue">Customers →</Link></div></header>{msg&&<p className="rounded-xl border bg-white p-4 font-bold">{msg}</p>}
 <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><span className="text-xs font-black uppercase tracking-widest text-slate-500">Follow-ups due</span><strong className="mt-2 block text-3xl">{due.length}</strong></div><div className="rounded-2xl border bg-white p-5"><span className="text-xs font-black uppercase tracking-widest text-slate-500">Active opportunities</span><strong className="mt-2 block text-3xl">{active.length}</strong></div><div className="rounded-2xl border bg-white p-5"><span className="text-xs font-black uppercase tracking-widest text-slate-500">Pipeline value</span><strong className="mt-2 block text-3xl">${pipeline.toFixed(2)}</strong></div></section>
 {due.length>0&&<section className="rounded-3xl border border-amber-300 bg-amber-50 p-6"><h2 className="font-serif text-3xl font-bold">Today’s sales worklist</h2><div className="mt-4 grid gap-3">{due.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white p-4"><div><strong>{r.business_name}</strong><p className="text-sm text-slate-600">Due {r.next_follow_up} · {r.stage.replaceAll("_"," ")}</p></div><button onClick={()=>void prepareDraft(r,"followup")} className="rounded-full border px-4 py-2 text-sm font-black">Prepare AI follow-up</button></div>)}</div></section>}
 <section className="grid gap-6 lg:grid-cols-[1fr_2fr]"><form onSubmit={add} className="grid content-start gap-3 rounded-3xl border bg-white p-6"><h2 className="font-serif text-3xl font-bold">Add lead</h2><input required name="business_name" placeholder="Business or organization"/><input name="contact_name" placeholder="Contact name"/><input name="email" type="email" placeholder="Email"/><input name="phone" placeholder="Phone"/><input name="source" placeholder="How we found them"/><input name="estimated_value" type="number" step="0.01" placeholder="Estimated value"/><label className="grid gap-1 font-bold">Next follow-up<input name="next_follow_up" type="date"/></label><textarea name="notes" rows={4} placeholder="What they may need, seasonal timing, prior contact"/><button className="hgn-btn-primary">Save lead</button></form><section className="grid gap-4">{rows.map(r=><article key={r.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-serif text-2xl font-bold">{r.business_name}</h2><p className="text-sm text-slate-600">{r.contact_name||"No contact"} · {r.email||r.phone||"No contact details"}</p></div>{r.estimated_value!==null&&<strong>${Number(r.estimated_value).toFixed(2)}</strong>}</div><div className="mt-3 flex flex-wrap gap-3 text-sm"><span>Stage: <strong>{r.stage.replaceAll("_"," ")}</strong></span><span>Follow-up: <strong>{r.next_follow_up||"Not set"}</strong></span>{r.source&&<span>Source: {r.source}</span>}</div>{r.notes&&<p className="mt-3 whitespace-pre-wrap text-sm text-slate-600">{r.notes}</p>}<div className="mt-4 flex flex-wrap gap-2">{stages.map(s=><button key={s} onClick={()=>void stage(r.id,s)} className={`rounded-full border px-3 py-2 text-xs font-black ${r.stage===s?"bg-slate-950 text-white":""}`}>{s.replaceAll("_"," ")}</button>)}</div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void prepareDraft(r,"followup")} className="rounded-full border px-3 py-2 text-xs font-black">AI follow-up draft</button><button onClick={()=>void prepareDraft(r,"renewal")} className="rounded-full border px-3 py-2 text-xs font-black">AI renewal draft</button></div></article>)}{!rows.length&&<p className="rounded-2xl border border-dashed p-8 text-center text-slate-500">No sales leads yet.</p>}</section></section></main>
}
